//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.02 at 10:10:34 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cern.ch/cms/csc/dw/ontology", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cern.cms.csc.dw.model.ontology;
