#!/bin/sh





CSC_VALUE=g_SYSTEM_NAME
echo -n CSCfw_ > rep
echo -n $CSC_VALUE > del
echo -n $CSC_VALUE >> rep


exit;

./file_editing_samplefilelist test1/test2/test3/*.ctl del rep > temp



g_SYSTEM_NAME2


g_SYSTEM_NAME


g_csc_part


g_MainLogicalFsmType
 

g_NodeLogicalFsmType


g_LIST_LOGICAL_DOMAINS
g_LIST_FSM_DOMAINS

g_EMAILS_GENERAL
g_EMAILS_HV
g_EMAILS_GAS
g_EMAILS_WTH


g_IS_ADJUST_TO_CONTROL_SIDE



g_IS_TEMPORAL_50V


g_HV_36CHANNEL_BOARDS_LIST
g_HV_36CHANNEL_BOARDS_CHAMBER_LIST



g_FULL_DPLIST


g_BROKER_HANDLERS_FIRST
g_STATUS_HANDLERS_FIRST
g_BLOCK_NEXT_DPCONNECT


g_wheel_labels
g_radius_labels
g_project_name_home
g_radius_labels_short
g_WHEELS
g_RADIUSES

g_IS_CALL_SELECT_HANDLER

g_alct_variables
g_cfeb_variables

g_csc_prefix


g_DEFINE_ELMB

g_DISPLAY_SAVED
g_GAS_ERROR_FLAG
g_GAS_WARNING_FLAG
g_CopyDimBrokerList

g_EMU_ALIASES
g_EMU_NAME_ALIASES

g_HV_STATUS
g_CURRENT_MASTER_INDEX

g_SLICE_DPOINTS
g_HV_LONG_TERM_DPOINTS

g_all_masters
g_all_1masters
g_all_2masters

g_host
g_1host
g_2host

EmuCmsSpecialMode
EmuCmsGlobalNode
EmuCmsGlobalType
EmuCmsGlobalCu
EmuCmsGlobalParent

g_all_primary

g_all_maratons
g_all_wieners12

g_FsmPanelMaxSizeX
g_FsmPanelMaxSizeY

g_HV_ID2PC_NAME
g_PCRATE_ID2PC_NAME
g_BROKER_DNS_MACHINE_NAMES
g_STATIONS_DNS_MACHINE_NAMES

g_dyn_debug1
g_dyn_debug2

g_master2chamber



g_last_time_wth_alarm

g_last_time_pt100_alarm

g_watch_mask



g_DEVICE_LIST
g_ACTIVE_DISKS_AND_CHAMBERS

