#!/bin/bash







#CSC_DIR_REP=/home/fast/pvss_fsm/scripts/libs/emu*.ctl
CSC_DIR_REP=test1/test2/test44/file*
#CSC_DIR_REP=/home/fast/pvss_fsm/scripts/libs/fw*/fw*.ctl
##CSC_DIR_REP=/home/fast/pvss_fsm/scripts/mudcs*.ctl

##CSC_DIR_REP=/home/fast/pvss_fsm/panels/*.pnl
##CSC_DIR_REP=/home/fast/pvss_fsm/panels/emu/*.pnl
##CSC_DIR_REP=/home/fast/pvss_fsm/panels/emu_config/*.pnl


function fun1(){

echo -n CSC_fwG_ > rep;
echo -n $CSC_VALUE > del;
echo -n $CSC_VALUE >> rep;
./file_editing_samplefilelist $CSC_DIR_REP del rep 
}




####./file_editing_samplefilelist test1/test2/test3/*.ctl del rep > temp

CSC_VALUE=g_SYSTEM_NAME
fun1

exit

CSC_VALUE=g_SYSTEM_NAME2
fun1



CSC_VALUE=g_csc_part
fun1

CSC_VALUE=g_MainLogicalFsmType
fun1 

CSC_VALUE=g_NodeLogicalFsmType
fun1

CSC_VALUE=g_LIST_LOGICAL_DOMAINS
fun1


CSC_VALUE=g_LIST_FSM_DOMAINS
fun1

CSC_VALUE=g_EMAILS_GENERAL
fun1


CSC_VALUE=g_EMAILS_HV
fun1


CSC_VALUE=g_EMAILS_GAS
fun1


CSC_VALUE=g_EMAILS_WTH
fun1

CSC_VALUE=g_IS_ADJUST_TO_CONTROL_SIDE
fun1


CSC_VALUE=g_IS_TEMPORAL_50V
fun1

CSC_VALUE=g_HV_36CHANNEL_BOARDS_LIST
fun1


CSC_VALUE=g_HV_36CHANNEL_BOARDS_CHAMBER_LIST
fun1


CSC_VALUE=g_FULL_DPLIST
fun1

CSC_VALUE=g_BROKER_HANDLERS_FIRST
fun1

CSC_VALUE=g_STATUS_HANDLERS_FIRST
fun1

CSC_VALUE=g_BLOCK_NEXT_DPCONNECT
fun1

CSC_VALUE=g_wheel_labels
fun1

CSC_VALUE=g_radius_labels
fun1

CSC_VALUE=g_project_name_home
fun1

CSC_VALUE=g_radius_labels_short
fun1

CSC_VALUE=g_WHEELS
fun1

CSC_VALUE=g_RADIUSES
fun1

CSC_VALUE=g_IS_CALL_SELECT_HANDLER
fun1

CSC_VALUE=g_alct_variables
fun1

CSC_VALUE=g_cfeb_variables
fun1

CSC_VALUE=g_csc_prefix
fun1

CSC_VALUE=g_DEFINE_ELMB
fun1


CSC_VALUE=g_DISPLAY_SAVED
fun1

CSC_VALUE=g_GAS_ERROR_FLAG
fun1

CSC_VALUE=g_GAS_WARNING_FLAG
fun1

CSC_VALUE=g_CopyDimBrokerList
fun1


CSC_VALUE=g_EMU_ALIASES
fun1

CSC_VALUE=g_EMU_NAME_ALIASES
fun1

CSC_VALUE=g_HV_STATUS
fun1

CSC_VALUE=g_CURRENT_MASTER_INDEX
fun1


CSC_VALUE=g_SLICE_DPOINTS
fun1

CSC_VALUE=g_HV_LONG_TERM_DPOINTS
fun1


CSC_VALUE=g_all_masters
fun1

CSC_VALUE=g_all_1masters
fun1

CSC_VALUE=g_all_2masters
fun1


CSC_VALUE=g_host
fun1

CSC_VALUE=g_1host
fun1

CSC_VALUE=g_2host
fun1


CSC_VALUE=EmuCmsSpecialMode
fun1

CSC_VALUE=EmuCmsGlobalNode


CSC_VALUE=EmuCmsGlobalType
fun1

CSC_VALUE=EmuCmsGlobalCu
fun1

CSC_VALUE=EmuCmsGlobalParent
fun1

CSC_VALUE=g_all_primary
fun1

CSC_VALUE=g_all_maratons
fun1

CSC_VALUE=g_all_wieners12
fun1

CSC_VALUE=g_FsmPanelMaxSizeX
fun1

CSC_VALUE=g_FsmPanelMaxSizeY
fun1

CSC_VALUE=g_HV_ID2PC_NAME


CSC_VALUE=g_PCRATE_ID2PC_NAME
fun1

CSC_VALUE=g_BROKER_DNS_MACHINE_NAMES
fun1

CSC_VALUE=g_STATIONS_DNS_MACHINE_NAMES
fun1


CSC_VALUE=g_dyn_debug1
fun1

CSC_VALUE=g_dyn_debug2
fun1


CSC_VALUE=g_master2chamber
fun1


CSC_VALUE=g_last_time_wth_alarm
fun1


CSC_VALUE=g_last_time_pt100_alarm
fun1


CSC_VALUE=g_watch_mask
fun1


CSC_VALUE=g_DEVICE_LIST
fun1


CSC_VALUE=g_ACTIVE_DISKS_AND_CHAMBERS
fun1
