#!/bin/sh








    mv /home/fast/pvss_fsm/panels/fwFSM/ui/fwFsmOperation.pnl /home/fast/pvss_fsm/panels/fwFSM/ui/fwFsmOperation_230.pnl
    mv /home/fast/pvss_fsm/panels/fwFSM/ui/fwFsmDomains.pnl /home/fast/pvss_fsm/panels/fwFSM/ui/fwFsmDomains_230.pnl
####    mv /home/fast/pvss_fsm/panels/fwFSM/ui/fwFsmObjects.pnl /home/fast/pvss_fsm/panels/fwFSM/ui/fwFsmObjects_230.pnl
    mv /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigatorLogical.pnl /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigatorLogical_230.pnl
    mv /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigatorHardware.pnl \
       /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigatorHardware_230.pnl
    mv /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigator.pnl \
       /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigator_230.pnl



    cp /home/fast/temp/pvss_fsm/panels/fwFSM/ui/fwFsmOperation.pnl /home/fast/pvss_fsm/panels/fwFSM/ui/.

    cp /home/fast/temp/pvss_fsm/panels/fwFSM/ui/fwFsmDomains.pnl /home/fast/pvss_fsm/panels/fwFSM/ui/.

    cp /home/fast/temp/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigatorLogical.pnl \ 
       /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/.

    cp /home/fast/temp/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigatorHardware.pnl \
       /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/.

    cp /home/fast/temp/pvss_fsm/panels/fwDeviceEditorNavigator/fwDeviceEditorNavigator.pnl \
       /home/fast/pvss_fsm/panels/fwDeviceEditorNavigator/.

    cp /home/fast/fwComponents_20060505/panels/fwFSMuser/fwUi.pnl /home/fast/pvss_fsm/panels/fwFSMuser/fwUi_236.pnl