//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.19 at 11:17:22 AM CEST 
//


package org.cern.cms.csc.exsys.re.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.cern.cms.csc.dw.model.base.EntityBase;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;


/**
 * <p>Java class for actionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeScheduled" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="timeDone" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="actionFactory" type="{http://www.cern.ch/cms/csc/exsys/re/model}actionFactoryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actionType", propOrder = {
    "timeScheduled",
    "timeDone",
    "actionFactory"
})
@Entity(name = "org.cern.cms.csc.exsys.re.model.Action")
@Table(name = "RE_ACTIONS")
@Inheritance(strategy = InheritanceType.JOINED)
public class Action
    extends EntityBase
    implements Serializable
{

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeScheduled;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeDone;
    @XmlElement(required = true)
    protected org.cern.cms.csc.exsys.re.model.ActionFactory actionFactory;
    @XmlAttribute(name = "id")
    protected Long id;

    /**
     * Gets the value of the timeScheduled property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getTimeScheduled() {
        return timeScheduled;
    }

    /**
     * Sets the value of the timeScheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeScheduled(XMLGregorianCalendar value) {
        this.timeScheduled = value;
    }

    @Transient
    public boolean isSetTimeScheduled() {
        return (this.timeScheduled!= null);
    }

    /**
     * Gets the value of the timeDone property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getTimeDone() {
        return timeDone;
    }

    /**
     * Sets the value of the timeDone property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeDone(XMLGregorianCalendar value) {
        this.timeDone = value;
    }

    @Transient
    public boolean isSetTimeDone() {
        return (this.timeDone!= null);
    }

    /**
     * Gets the value of the actionFactory property.
     * 
     * @return
     *     possible object is
     *     {@link org.cern.cms.csc.exsys.re.model.ActionFactory }
     *     
     */
    @ManyToOne(targetEntity = org.cern.cms.csc.exsys.re.model.ActionFactory.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "REA_ACTION_FACTORY_ID", nullable = false)
    public org.cern.cms.csc.exsys.re.model.ActionFactory getActionFactory() {
        return actionFactory;
    }

    /**
     * Sets the value of the actionFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.cern.cms.csc.exsys.re.model.ActionFactory }
     *     
     */
    public void setActionFactory(org.cern.cms.csc.exsys.re.model.ActionFactory value) {
        this.actionFactory = value;
    }

    @Transient
    public boolean isSetActionFactory() {
        return (this.actionFactory!= null);
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "REA_ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    @SequenceGenerator(name = "RE_ACTION_ID_SEQ", sequenceName = "RE_ACTION_ID_SEQ")
    public Long getid() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setid(Long value) {
        this.id = value;
    }

    @Basic
    @Column(name = "REA_TIME_SCHEDULED")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getTimeScheduledItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getTimeScheduled());
    }

    public void setTimeScheduledItem(Date target) {
        setTimeScheduled(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    @Basic
    @Column(name = "REA_TIME_DONE")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getTimeDoneItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getTimeDone());
    }

    public void setTimeDoneItem(Date target) {
        setTimeDone(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

}
