//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.exsys.re.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.cern.cms.csc.dw.model.base.EntityBase;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;


/**
 * <p>Java class for conclusionTriggerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conclusionTriggerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.cern.ch/cms/csc/exsys/re/model}conclusionTriggerTypeType"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="rule" type="{http://www.cern.ch/cms/csc/exsys/re/model}ruleType"/>
 *         &lt;element name="conclusion" type="{http://www.cern.ch/cms/csc/exsys/re/model}conclusionType"/>
 *         &lt;element name="sources" type="{http://www.cern.ch/cms/csc/exsys/re/model}conclusionTriggerSourceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conclusionTriggerType", propOrder = {
    "type",
    "timestamp",
    "rule",
    "conclusion",
    "sources"
})
@Entity(name = "org.cern.cms.csc.exsys.re.model.ConclusionTrigger")
@Table(name = "RE_CONCLUSION_TRIGGERS")
@Inheritance(strategy = InheritanceType.JOINED)
public class ConclusionTrigger
    extends EntityBase
    implements Serializable
{

    @XmlElement(required = true)
    protected ConclusionTriggerType type;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected org.cern.cms.csc.exsys.re.model.Rule rule;
    @XmlElement(required = true)
    protected org.cern.cms.csc.exsys.re.model.Conclusion conclusion;
    protected List<ConclusionTriggerSource> sources = new Vector<ConclusionTriggerSource>();
    @XmlAttribute(name = "id")
    protected Long id;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ConclusionTriggerType }
     *     
     */
    @Transient
    public ConclusionTriggerType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConclusionTriggerType }
     *     
     */
    public void setType(ConclusionTriggerType value) {
        this.type = value;
    }

    @Transient
    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    @Transient
    public boolean isSetTimestamp() {
        return (this.timestamp!= null);
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link org.cern.cms.csc.exsys.re.model.Rule }
     *     
     */
    @ManyToOne(targetEntity = org.cern.cms.csc.exsys.re.model.Rule.class)
    @JoinColumn(name = "RECT_RULE_ID", nullable = false)
    public org.cern.cms.csc.exsys.re.model.Rule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.cern.cms.csc.exsys.re.model.Rule }
     *     
     */
    public void setRule(org.cern.cms.csc.exsys.re.model.Rule value) {
        this.rule = value;
    }

    @Transient
    public boolean isSetRule() {
        return (this.rule!= null);
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link org.cern.cms.csc.exsys.re.model.Conclusion }
     *     
     */
    @ManyToOne(targetEntity = org.cern.cms.csc.exsys.re.model.Conclusion.class)
    @JoinColumn(name = "RECT_CONCLUSION_ID", nullable = false)
    public org.cern.cms.csc.exsys.re.model.Conclusion getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.cern.cms.csc.exsys.re.model.Conclusion }
     *     
     */
    public void setConclusion(org.cern.cms.csc.exsys.re.model.Conclusion value) {
        this.conclusion = value;
    }

    @Transient
    public boolean isSetConclusion() {
        return (this.conclusion!= null);
    }

    /**
     * Gets the value of the sources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConclusionTriggerSource }
     * 
     * 
     */
    @OneToMany(targetEntity = ConclusionTriggerSource.class, cascade = {
        CascadeType.ALL
    }, mappedBy = "trigger")
    @JoinColumn(name = "RECS_TRIGGER_ID", nullable = false)
    public List<ConclusionTriggerSource> getSources() {
        if (sources == null) {
            sources = new Vector<ConclusionTriggerSource>();
        }
        return this.sources;
    }

    /**
     * 
     * 
     */
    public void setSources(List<ConclusionTriggerSource> sources) {
        this.sources = sources;
    }

    @Transient
    public boolean isSetSources() {
        return ((this.sources!= null)&&(!this.sources.isEmpty()));
    }

    public void unsetSources() {
        this.sources = null;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "RECT_ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    @SequenceGenerator(name = "RE_CONCL_TRIGGER_ID_SEQ", sequenceName = "RE_CONCL_TRIGGER_ID_SEQ")
    public Long getid() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setid(Long value) {
        this.id = value;
    }

    @Basic
    @Column(name = "RECT_TYPE", length = 6)
    public String getTypeItem() {
        return ((this.getType() == null)?null:this.getType().value());
    }

    public void setTypeItem(String target) {
        setType(((target == null)?null:ConclusionTriggerType.fromValue(target)));
    }

    @Basic
    @Column(name = "RECT_TIMESTAMP", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    public Date getTimestampItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getTimestamp());
    }

    public void setTimestampItem(Date target) {
        setTimestamp(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

}
