//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cern.cms.csc.dw.model.annotation.FactAnn;


/**
 * <p>Java class for DcsDisableEnableFactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DcsDisableEnableFactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cern.ch/cms/csc/dw/model}dcsFactType">
 *       &lt;sequence>
 *         &lt;element name="isDisabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DcsDisableEnableFactType", propOrder = {
    "disabled"
})
@Entity(name = "DcsDisableEnableFact")
@Table(name = "CDW_DCS_DISABLE_ENABLE_FACTS")
@FactAnn(title = "Device disable and enable facts")
public class DcsDisableEnableFact
    extends DcsFact
    implements Serializable
{

    @XmlElement(name = "isDisabled")
    protected boolean disabled;

    /**
     * Gets the value of the disabled property.
     * 
     */
    @Basic
    @Column(name = "FCT_IS_DISABLED", nullable = false)
    public boolean isDisabled() {
        return disabled;
    }

    /**
     * Sets the value of the disabled property.
     * 
     */
    public void setDisabled(boolean value) {
        this.disabled = value;
    }

    @Transient
    public boolean isSetDisabled() {
        return true;
    }

}
