//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for factRequestCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="factRequestCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element ref="{http://www.cern.ch/cms/csc/dw/model}factRequest" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "factRequestCollectionType", propOrder = {
    "requestId",
    "factRequest"
})
public class FactRequestCollection
    implements Serializable
{

    protected long requestId;
    @XmlElement(required = true)
    protected List<FactRequest> factRequest = new Vector<FactRequest>();

    /**
     * Gets the value of the requestId property.
     * 
     */
    public long getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     */
    public void setRequestId(long value) {
        this.requestId = value;
    }

    public boolean isSetRequestId() {
        return true;
    }

    /**
     * Gets the value of the factRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the factRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFactRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FactRequest }
     * 
     * 
     */
    public List<FactRequest> getFactRequest() {
        if (factRequest == null) {
            factRequest = new Vector<FactRequest>();
        }
        return this.factRequest;
    }

    /**
     * 
     * 
     */
    public void setFactRequest(List<FactRequest> factRequest) {
        this.factRequest = factRequest;
    }

    public boolean isSetFactRequest() {
        return ((this.factRequest!= null)&&(!this.factRequest.isEmpty()));
    }

    public void unsetFactRequest() {
        this.factRequest = null;
    }

}
