//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cern.cms.csc.dw.model.annotation.FactAnn;


/**
 * <p>Java class for FEDFSMFactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FEDFSMFactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cern.ch/cms/csc/dw/model}factType">
 *       &lt;sequence>
 *         &lt;element name="from" type="{http://www.cern.ch/cms/csc/dw/model}fedFsmStateType"/>
 *         &lt;element name="to" type="{http://www.cern.ch/cms/csc/dw/model}fedFsmStateType"/>
 *         &lt;element name="configType" type="{http://www.cern.ch/cms/csc/dw/model}fedConfigTypeType"/>
 *         &lt;element name="configValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result" type="{http://www.cern.ch/cms/csc/dw/model}fedStateTransitionResultType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FEDFSMFactType", propOrder = {
    "from",
    "to",
    "configType",
    "configValue",
    "result"
})
@Entity(name = "org.cern.cms.csc.dw.model.fact.FedFsmFact")
@Table(name = "CDW_FED_FSM_FACTS")
@FactAnn(limitComponents = {
    "FEDSystem"
}, title = "FED FSM State Transition")
public class FedFsmFact
    extends Fact
    implements Serializable
{

    @XmlElement(required = true)
    protected FedFsmState from;
    @XmlElement(required = true)
    protected FedFsmState to;
    @XmlElement(required = true)
    protected FedConfigType configType;
    @XmlElement(required = true)
    protected String configValue;
    @XmlElement(required = true)
    protected FedStateTransitionResult result;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link FedFsmState }
     *     
     */
    @Basic
    @Column(name = "FCT_FROM", length = 16)
    @Enumerated(EnumType.STRING)
    public FedFsmState getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link FedFsmState }
     *     
     */
    public void setFrom(FedFsmState value) {
        this.from = value;
    }

    @Transient
    public boolean isSetFrom() {
        return (this.from!= null);
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link FedFsmState }
     *     
     */
    @Basic
    @Column(name = "FCT_TO", length = 16)
    @Enumerated(EnumType.STRING)
    public FedFsmState getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link FedFsmState }
     *     
     */
    public void setTo(FedFsmState value) {
        this.to = value;
    }

    @Transient
    public boolean isSetTo() {
        return (this.to!= null);
    }

    /**
     * Gets the value of the configType property.
     * 
     * @return
     *     possible object is
     *     {@link FedConfigType }
     *     
     */
    @Basic
    @Column(name = "FCT_CONFIG_TYPE", length = 10)
    @Enumerated(EnumType.STRING)
    public FedConfigType getConfigType() {
        return configType;
    }

    /**
     * Sets the value of the configType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FedConfigType }
     *     
     */
    public void setConfigType(FedConfigType value) {
        this.configType = value;
    }

    @Transient
    public boolean isSetConfigType() {
        return (this.configType!= null);
    }

    /**
     * Gets the value of the configValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FCT_CONFIG_VALUE", length = 255)
    public String getConfigValue() {
        return configValue;
    }

    /**
     * Sets the value of the configValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigValue(String value) {
        this.configValue = value;
    }

    @Transient
    public boolean isSetConfigValue() {
        return (this.configValue!= null);
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link FedStateTransitionResult }
     *     
     */
    @Basic
    @Column(name = "FCT_RESULT", length = 10)
    @Enumerated(EnumType.STRING)
    public FedStateTransitionResult getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link FedStateTransitionResult }
     *     
     */
    public void setResult(FedStateTransitionResult value) {
        this.result = value;
    }

    @Transient
    public boolean isSetResult() {
        return (this.result!= null);
    }

}
