//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cern.cms.csc.dw.model.annotation.FactAnn;


/**
 * <p>Java class for FedRepeatErrorFactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FedRepeatErrorFactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cern.ch/cms/csc/dw/model}factType">
 *       &lt;sequence>
 *         &lt;element name="chambersInError" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numChambersInError" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FedRepeatErrorFactType", propOrder = {
    "chambersInError",
    "numChambersInError"
})
@Entity(name = "org.cern.cms.csc.dw.model.fact.FedRepeatErrorFact")
@Table(name = "CDW_FED_REPEATED_ERROR_FACTS")
@FactAnn(limitComponents = {
    "Endcap"
}, title = "List of chambers that are repeatedly giving errors at the DDU (they are automatically included in the FMM ignore list by the FED software)")
public class FedRepeatErrorFact
    extends Fact
    implements Serializable
{

    @XmlElement(required = true)
    protected String chambersInError;
    @XmlElement(required = true)
    protected BigInteger numChambersInError;

    /**
     * Gets the value of the chambersInError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FCT_CHAMBERS_IN_ERROR", length = 1300)
    public String getChambersInError() {
        return chambersInError;
    }

    /**
     * Sets the value of the chambersInError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChambersInError(String value) {
        this.chambersInError = value;
    }

    @Transient
    public boolean isSetChambersInError() {
        return (this.chambersInError!= null);
    }

    /**
     * Gets the value of the numChambersInError property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_NUM_CHAMBERS_IN_ERROR", precision = 10, scale = 0)
    public BigInteger getNumChambersInError() {
        return numChambersInError;
    }

    /**
     * Sets the value of the numChambersInError property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumChambersInError(BigInteger value) {
        this.numChambersInError = value;
    }

    @Transient
    public boolean isSetNumChambersInError() {
        return (this.numChambersInError!= null);
    }

}
