#define HIST_LAYER_LOW_LIMIT0        0.
#define HIST_LAYER_LOW_LIMIT1        0.
#define HIST_LAYER_HIGH_LIMIT0      200.
#define HIST_LAYER_HIGH_LIMIT1      200.

#define HIST_SUMMARY_LOW_LIMIT0      0.
#define HIST_SUMMARY_LOW_LIMIT1      0.
#define HIST_SUMMARY_HIGH_LIMIT0     200.
#define HIST_SUMMARY_HIGH_LIMIT1     200.

#define HIST_PROB_LAYER_LOW_LIMIT0        0.
#define HIST_PROB_LAYER_LOW_LIMIT1        0.
#define HIST_PROB_LAYER_HIGH_LIMIT0       1.1
#define HIST_PROB_LAYER_HIGH_LIMIT1       1.1

#define HIST_PROB_SUMMARY_LOW_LIMIT0      0.
#define HIST_PROB_SUMMARY_LOW_LIMIT1      0.
#define HIST_PROB_SUMMARY_HIGH_LIMIT0     1.1
#define HIST_PROB_SUMMARY_HIGH_LIMIT1     1.1

#define SINGLES_RATE_LOWER_LIMIT0    1.
#define SINGLES_RATE_LOWER_LIMIT1    1.
#define SINGLES_RATE_UPPER_LIMIT0   100.
#define SINGLES_RATE_UPPER_LIMIT1   150.

#define ISOLATED_PROB_LOWER_LIMIT0    0.1
#define ISOLATED_PROB_LOWER_LIMIT1    0.1
#define ISOLATED_PROB_UPPER_LIMIT0    1.0
#define ISOLATED_PROB_UPPER_LIMIT1    1.0
