#define DAC_SCAN          2
#define DELAY_SCAN        3

#define REL_TIME_FRAME_BOTTOM -100.0
#define REL_TIME_FRAME_UP 100.0
#define REL_TIME_FRAME_BOTTOM_SUM -100.0
#define REL_TIME_FRAME_UP_SUM 100.0
#define REL_TIME_BOTTOM_BOUND -50.0
#define REL_TIME_UP_BOUND 50.0

#define AMPL_FRAME_BOTTOM 500.0
#define AMPL_FRAME_UP 1950.0
#define AMPL_FRAME_BOTTOM_SUM 500.0
#define AMPL_FRAME_UP_SUM 1950.0
#define AMPL_BOTTOM_BOUND 850.0
#define AMPL_UP_BOUND 1600.0

#define Q_FRAME_BOTTOM 1.4
#define Q_FRAME_UP 3.6
#define Q_FRAME_BOTTOM_SUM 1.4
#define Q_FRAME_UP_SUM 3.6
#define Q_BOTTOM_BOUND 2.0
#define Q_UP_BOUND 3.0

#define LXT_FRAME_BOTTOM -0.1
#define LXT_FRAME_UP 0.2
#define LXT_FRAME_BOTTOM_SUM -0.1
#define LXT_FRAME_UP_SUM 0.2
#define LXT_BOTTOM_BOUND 0.05
#define LXT_UP_BOUND 0.15

#define RXT_FRAME_BOTTOM -0.1
#define RXT_FRAME_UP 0.2
#define RXT_FRAME_BOTTOM_SUM -0.1
#define RXT_FRAME_UP_SUM 0.2
#define RXT_BOTTOM_BOUND 0.05
#define RXT_UP_BOUND 0.15

#define LRXT_FRAME_BOTTOM -0.0025
#define LRXT_FRAME_UP 0.001
#define LRXT_FRAME_BOTTOM_SUM -0.0025
#define LRXT_FRAME_UP_SUM 0.001
#define LRXT_BOTTOM_BOUND -0.0015
#define LRXT_UP_BOUND 0.0

#define DAC2FC 0.0952 //=> ...*0.125 -> 0.0952 

#define SLOPE_FRAME_BOTTOM 0.0
#define SLOPE_FRAME_UP 8.0
#define SLOPE_FRAME_BOTTOM_SUM 0.0
#define SLOPE_FRAME_UP_SUM 8.0
#define SLOPE_BOTTOM_BOUND 1.9
#define SLOPE_UP_BOUND 6.0

#define INTERCEPT_FRAME_BOTTOM -190.
#define INTERCEPT_FRAME_UP 190.
#define INTERCEPT_FRAME_BOTTOM_SUM -190.
#define INTERCEPT_FRAME_UP_SUM 190.
#define INTERCEPT_BOTTOM_BOUND -155.
#define INTERCEPT_UP_BOUND 155.

#define RMS_FRAME_BOTTOM -5.0
#define RMS_FRAME_UP 16.0
#define RMS_FRAME_BOTTOM_SUM -5.0
#define RMS_FRAME_UP_SUM 16.0
#define RMS_BOTTOM_BOUND 0.0
#define RMS_UP_BOUND 12.0


