  CREATE TABLE "EMUCDB_FSM_TYPES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMUCDB_FSM_TYPES_PK" PRIMARY KEY ("ID") ENABLE
   )
 ;

  CREATE SEQUENCE "EMUCDB_FSM_TYPES_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE ;
 ;

  CREATE OR REPLACE TRIGGER "EMUCDB_FSM_TYPES_SEQ_TRIG" before insert on "EMUCDB_FSM_TYPES"    for each row begin     if inserting then       if :NEW."ID" is null then          select EMUCDB_FSM_TYPES_SEQ.nextval into :NEW."ID" from dual;       end if;    end if; end;
 ;

  ALTER TRIGGER "EMUCDB_FSM_TYPES_SEQ_TRIG" ENABLE;
 ;

  ALTER TABLE 
    ITEMS 
  ADD (
    FSM_TYPE number,
    CONSTRAINT "ITEMS_FK_FSM_TYPES" FOREIGN KEY ("FSM_TYPE")
      REFERENCES "EMUCDB_FSM_TYPES" ("ID") ENABLE
  )
 ;

  CREATE TABLE "EMUCDB_PARAMETERS" 
   (	"NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMUCDB_PARAMETERS_PK" PRIMARY KEY ("NAME") ENABLE
   )
 ;

  INSERT INTO EMUCDB_PARAMETERS(NAME, VALUE) VALUES ('emucdb_version', '0.3')
 ;
