use hvdb;
select CSC.NAME, MAP.RDB, MAP.RDB_PART, HVCARD.DATASLOT, RDB.ADDR, MAP.MASTER, MHVCARD.DATASLOT, MASTERDB.ADDR, MAP.MASTER_CHAN  from MAP, CSC, RDB, MASTERDB, HVCARD, HVCARD as MHVCARD where ((MAP.CSC=CSC.ID) and (MAP.RDB=RDB.ID) and (MAP.MASTER=MASTERDB.ID) and (RDB.HOSTCARD=HVCARD.ID) and (MASTERDB.HOSTCARD=MHVCARD.ID)) order by CSC.NAME;
