#!/bin/bash









#CSC_VALUE=CRB_2
#CSC_VALUE=EMUNodes
#CSC_VALUE=EMUTREENOdes

#NEW_VALUE=fwCrb_CSC_LV
#NEW_VALUE=CSC_LV_NODES
#NEW_VALUE=CSC_LV_TREE_NODES

function fun1(){

echo -n $NEW_VALUE > rep;
echo -n $CSC_VALUE > del;
#echo -n $CSC_VALUE >> rep;
file_editing_samplefilelist $CSC_DIR_REP del rep > temp
}



####./file_editing_samplefilelist test1/test2/test3/*.ctl del rep > temp

function fun2(){

CSC_DIR_REP=/home/fast/test_36_mrtn_today/panels/*.pnl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/panels/*/*.pnl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/panels/*/*/*.pnl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/panels/*/*/*/*.pnl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/panels/*/*/*/*/*.pnl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/panels/*/*/*/*/*/*.pnl
fun1
#---------------------------------------------------------------
CSC_DIR_REP=/home/fast/test_36_mrtn_today/scripts/*.ctl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/scripts/*/*.ctl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/scripts/*/*/*.ctl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/scripts/*/*/*/*.ctl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/scripts/*/*/*/*/*.ctl
fun1
CSC_DIR_REP=/home/fast/test_36_mrtn_today/scripts/*/*/*/*/*/*.ctl
fun1

}
#------------------------------------------------------------------


#CSC_VALUE=CRB_2
#NEW_VALUE=fwCrb_CSC_LV
#fun2

#------------------------------------------------------------------



CSC_VALUE=EMUNodes
NEW_VALUE=CSC_LV_NODES
fun2

#------------------------------------------------------------------


CSC_VALUE=EMUTREENodes
NEW_VALUE=CSC_LV_TREE_NODES
fun2

