//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 03:34:10 PM CET 
//


package org.cern.cms.csc.dw.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cern.cms.csc.dw.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fact_QNAME = new QName("http://www.cern.org/cms/csc/dw/model", "fact");
    private final static QName _SlidingTmbTriggerCounterFact_QNAME = new QName("http://www.cern.org/cms/csc/dw/model", "slidingTmbTriggerCounterFact");
    private final static QName _FactCollection_QNAME = new QName("http://www.cern.org/cms/csc/dw/model", "factCollection");
    private final static QName _CumulativeTmbTriggerCounterFact_QNAME = new QName("http://www.cern.org/cms/csc/dw/model", "cumulativeTmbTriggerCounterFact");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cern.cms.csc.dw.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CumulativeTmbTriggerCounterFactType }
     * 
     */
    public CumulativeTmbTriggerCounterFactType createCumulativeTmbTriggerCounterFactType() {
        return new CumulativeTmbTriggerCounterFactType();
    }

    /**
     * Create an instance of {@link FactCollectionType }
     * 
     */
    public FactCollectionType createFactCollectionType() {
        return new FactCollectionType();
    }

    /**
     * Create an instance of {@link SlidingTmbTriggerCounterFactType }
     * 
     */
    public SlidingTmbTriggerCounterFactType createSlidingTmbTriggerCounterFactType() {
        return new SlidingTmbTriggerCounterFactType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cern.org/cms/csc/dw/model", name = "fact")
    public JAXBElement<FactType> createFact(FactType value) {
        return new JAXBElement<FactType>(_Fact_QNAME, FactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlidingTmbTriggerCounterFactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cern.org/cms/csc/dw/model", name = "slidingTmbTriggerCounterFact", substitutionHeadNamespace = "http://www.cern.org/cms/csc/dw/model", substitutionHeadName = "fact")
    public JAXBElement<SlidingTmbTriggerCounterFactType> createSlidingTmbTriggerCounterFact(SlidingTmbTriggerCounterFactType value) {
        return new JAXBElement<SlidingTmbTriggerCounterFactType>(_SlidingTmbTriggerCounterFact_QNAME, SlidingTmbTriggerCounterFactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FactCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cern.org/cms/csc/dw/model", name = "factCollection")
    public JAXBElement<FactCollectionType> createFactCollection(FactCollectionType value) {
        return new JAXBElement<FactCollectionType>(_FactCollection_QNAME, FactCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CumulativeTmbTriggerCounterFactType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cern.org/cms/csc/dw/model", name = "cumulativeTmbTriggerCounterFact", substitutionHeadNamespace = "http://www.cern.org/cms/csc/dw/model", substitutionHeadName = "fact")
    public JAXBElement<CumulativeTmbTriggerCounterFactType> createCumulativeTmbTriggerCounterFact(CumulativeTmbTriggerCounterFactType value) {
        return new JAXBElement<CumulativeTmbTriggerCounterFactType>(_CumulativeTmbTriggerCounterFact_QNAME, CumulativeTmbTriggerCounterFactType.class, null, value);
    }

}
