<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:sched="http://schemas.sun.com/jbi/wsdl-extensions/scheduler/"
    name="pullTmbCountersScheduler" targetNamespace="http://www.cern.ch/cms/csc/exsys/wsdl/pullTmbCountersScheduler" xmlns:tns="http://www.cern.ch/cms/csc/exsys/wsdl/pullTmbCountersScheduler" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <wsdl:types/>
    <wsdl:message name="TriggerEventMessage">
        <wsdl:part name="schedPart" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="TriggerPortType">
        <wsdl:operation name="FireTriggerOperation">
            <wsdl:input name="inMsg" message="tns:TriggerEventMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="TriggerBinding" type="tns:TriggerPortType">
        <sched:binding group="pullTmbCountersScheduler" date-format="yyyy-MM-dd&apos;T&apos;HH:mm:ss.SSSZ"/>
        <wsdl:operation name="FireTriggerOperation">
            <sched:operation mode="static"/>
            <wsdl:input name="inMsg">
                <!-- local tunnel -->
                <!--sched:trigger name="pullMinusSideTmbTriggerCounters" type="simple" enabled="true" description="Pulls TMB trigger counters for minus side" repeat="indefinite" interval="30000" message="http://localhost:20044/urn:xdaq-application:lid=30/XmlOutput"/-->
                <!--sched:trigger name="pullMinusSideTmbAllCounters" type="simple" enabled="true" description="Pulls TMB all counters for minus side" repeat="indefinite" interval="30000" message="http://localhost:20044/urn:xdaq-application:lid=30/DatabaseOutput"/-->
                <!-- =========== -->
                <!-- P5 - production -->
                <sched:trigger name="pullPlusSideTmbTriggerCounters" type="simple" enabled="true" description="Pulls TMB trigger counters for plus side" repeat="indefinite" interval="30000" message="http://csc-dcs-pc1:20040/urn:xdaq-application:lid=30/XmlOutput"/>
                <sched:trigger name="pullPlusSideTmbAllCounters" type="simple" enabled="true" description="Pulls all TMB counters for plus side" repeat="indefinite" interval="30000" message="http://csc-dcs-pc1:20040/urn:xdaq-application:lid=30/DatabaseOutput"/>
                <sched:trigger name="pullMinusSideTmbTriggerCounters" type="simple" enabled="true" description="Pulls TMB trigger counters for minus side" repeat="indefinite" interval="30000" message="http://csc-dcs-pc2:20040/urn:xdaq-application:lid=30/XmlOutput"/>
                <sched:trigger name="pullMinusSideTmbAllCounters" type="simple" enabled="true" description="Pulls all TMB counters for minus side" repeat="indefinite" interval="30000" message="http://csc-dcs-pc2:20040/urn:xdaq-application:lid=30/DatabaseOutput"/>
                <!-- =========== -->
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="TriggerService">
        <wsdl:port name="pullTmbCountersScheduler_TriggerPort" binding="tns:TriggerBinding">
            <sched:active-period starting="now" ending="never"/>
        </wsdl:port>
    </wsdl:service>
    <plnk:partnerLinkType name="pullTmbCountersScheduler">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="TriggerPortTypeRole" portType="tns:TriggerPortType"/>
    </plnk:partnerLinkType>
</wsdl:definitions>
