//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cern.cms.csc.dw.model.annotation.FactAnn;


/**
 * <p>Java class for DcsAlctLvFactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DcsAlctLvFactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cern.ch/cms/csc/dw/model}factType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="current_1v8" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DcsAlctLvFactType", propOrder = {
    "status",
    "current1V8"
})
@Entity(name = "org.cern.cms.csc.dw.model.fact.DcsAlctLvFact")
@Table(name = "CDW_DCS_ALCT_LV_FACTS")
@FactAnn(limitComponents = {
    "ALCT"
}, title = "ALCT LV data")
public class DcsAlctLvFact
    extends Fact
    implements Serializable
{

    @XmlElement(required = true)
    protected BigInteger status;
    @XmlElement(name = "current_1v8")
    protected double current1V8;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_DATA_STATUS", precision = 10, scale = 0)
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }

    @Transient
    public boolean isSetStatus() {
        return (this.status!= null);
    }

    /**
     * Gets the value of the current1V8 property.
     * 
     */
    @Basic
    @Column(name = "FCT_CURRENT_1V8", precision = 20, scale = 10)
    public double getCurrent1V8() {
        return current1V8;
    }

    /**
     * Sets the value of the current1V8 property.
     * 
     */
    public void setCurrent1V8(double value) {
        this.current1V8 = value;
    }

    @Transient
    public boolean isSetCurrent1V8() {
        return true;
    }

}
