//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cern.cms.csc.dw.model.annotation.FactAnn;


/**
 * <p>Java class for DDUFMMResetFactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DDUFMMResetFactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cern.ch/cms/csc/dw/model}factType">
 *       &lt;sequence>
 *         &lt;element name="crateNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DDUFMMResetFactType", propOrder = {
    "crateNumber"
})
@Entity(name = "org.cern.cms.csc.dw.model.fact.DduFmmResetFact")
@Table(name = "CDW_DDU_FMM_RESET_FACTS")
@FactAnn(limitComponents = {
    "FEDCrate",
    "DDU"
}, title = "FMM IRQ Reset Detection")
public class DduFmmResetFact
    extends Fact
    implements Serializable
{

    @XmlElement(required = true)
    protected BigInteger crateNumber;

    /**
     * Gets the value of the crateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_CRATE_NUMBER", precision = 3, scale = 0)
    public BigInteger getCrateNumber() {
        return crateNumber;
    }

    /**
     * Sets the value of the crateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrateNumber(BigInteger value) {
        this.crateNumber = value;
    }

    @Transient
    public boolean isSetCrateNumber() {
        return (this.crateNumber!= null);
    }

}
