//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.13 at 06:44:15 PM CET 
//


package org.cern.cms.csc.dw.model.fact;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for factTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="factTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="slidingTmbTriggerCounterFact"/>
 *     &lt;enumeration value="cumulativeTmbTriggerCounterFact"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "factTypeType")
@XmlEnum
public enum FactType {

    @XmlEnumValue("slidingTmbTriggerCounterFact")
    SLIDING_TMB_TRIGGER_COUNTER_FACT("slidingTmbTriggerCounterFact"),
    @XmlEnumValue("cumulativeTmbTriggerCounterFact")
    CUMULATIVE_TMB_TRIGGER_COUNTER_FACT("cumulativeTmbTriggerCounterFact");
    private final String value;

    FactType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FactType fromValue(String v) {
        for (FactType c: FactType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
