//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.04 at 05:42:02 PM CEST 
//


package org.cern.cms.csc.dw.model.fact;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DCS"/>
 *     &lt;enumeration value="LOCAL_DQM"/>
 *     &lt;enumeration value="LOCAL_DAQ"/>
 *     &lt;enumeration value="FED"/>
 *     &lt;enumeration value="Xmas"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sourceType")
@XmlEnum
public enum SourceType {

    DCS("DCS"),
    @XmlEnumValue("LOCAL_DQM")
    LOCAL___DQM("LOCAL_DQM"),
    @XmlEnumValue("LOCAL_DAQ")
    LOCAL___DAQ("LOCAL_DAQ"),
    FED("FED"),
    @XmlEnumValue("Xmas")
    XMAS("Xmas");
    private final String value;

    SourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceType fromValue(String v) {
        for (SourceType c: SourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
