drop table CDW_DDL
/

CREATE TABLE CDW_DDL (
    OBJECT_TYPE VARCHAR2(30 BYTE) NOT NULL ENABLE,
    OBJECT_NAME VARCHAR2(30 BYTE) NOT NULL ENABLE,
    DDL CLOB NOT NULL ENABLE,
    GRANTS CLOB,
    CONSTRAINT CDW_DDL_PK PRIMARY KEY (OBJECT_TYPE, OBJECT_NAME)
)
/

ALTER TABLE CDW_FACT_COLLECTION_ITEMS ADD (FIT_TIME DATE DEFAULT sysdate NOT NULL)
/

ALTER TABLE CDW_FACT_COLLECTIONS MODIFY (FCO_TIME DEFAULT current_timestamp NOT NULL)
/

ALTER TABLE CDW_FACT_COLLECTIONS MODIFY (FCO_CMP_ID NOT NULL)
/

ALTER TABLE CDW_FACT_COLLECTION_ITEMS MODIFY (FIT_TYPE NOT NULL)
/

ALTER TABLE CDW_FACT_COLLECTION_ITEMS MODIFY (FIT_FCT_ID NOT NULL)
/
