//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.14 at 12:26:53 AM CET 
//


package ch.cern.cms.csc.cdw.data;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.hyperjaxb3.xml.bind.JAXBElementUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for factCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="factCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source" type="{http://www.cern.ch/cms/csc/cdw/data}sourceType"/>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element ref="{http://www.cern.ch/cms/csc/cdw/data}fact" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "factCollectionType", propOrder = {
    "source",
    "requestId",
    "fact"
})
@Entity(name = "ch.cern.cms.csc.cdw.data.FactCollectionType")
@Table(name = "FACTCOLLECTIONTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class FactCollectionType
    implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected SourceType source;
    protected Long requestId;
    @XmlElementRef(name = "fact", namespace = "http://www.cern.ch/cms/csc/cdw/data", type = JAXBElement.class)
    protected List<JAXBElement<? extends FactType>> fact;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    protected transient List<FactCollectionType.FactCollectionTypeFactItem> factItems;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    @Basic
    @Column(name = "SOURCE_", length = 255)
    @Enumerated(EnumType.STRING)
    public SourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    public void setSource(SourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Basic
    @Column(name = "REQUESTID", precision = 20, scale = 10)
    public Long getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRequestId(Long value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the fact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SlidingTmbTriggerCounterFactType }{@code >}
     * {@link JAXBElement }{@code <}{@link CumulativeTmbTriggerCounterFactType }{@code >}
     * {@link JAXBElement }{@code <}{@link FactType }{@code >}
     * 
     * 
     */
    @Transient
    public List<JAXBElement<? extends FactType>> getFact() {
        if (fact == null) {
            fact = new ArrayList<JAXBElement<? extends FactType>>();
        }
        return this.fact;
    }

    /**
     * 
     * 
     */
    public void setFact(List<JAXBElement<? extends FactType>> fact) {
        this.fact = fact;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = ch.cern.cms.csc.cdw.data.FactCollectionType.FactCollectionTypeFactItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "FACTITEMS_FACTCOLLECTIONTYPE_0")
    public List<FactCollectionType.FactCollectionTypeFactItem> getFactItems() {
        if (this.factItems == null) {
            this.factItems = new ArrayList<FactCollectionType.FactCollectionTypeFactItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.fact)) {
            this.fact = ItemUtils.wrap(this.fact, this.factItems, FactCollectionType.FactCollectionTypeFactItem.class);
        }
        return this.factItems;
    }

    public void setFactItems(List<FactCollectionType.FactCollectionTypeFactItem> value) {
        this.fact = null;
        this.factItems = null;
        this.factItems = value;
        if (this.factItems == null) {
            this.factItems = new ArrayList<FactCollectionType.FactCollectionTypeFactItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.fact)) {
            this.fact = ItemUtils.wrap(this.fact, this.factItems, FactCollectionType.FactCollectionTypeFactItem.class);
        }
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof FactCollectionType)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final FactCollectionType that = ((FactCollectionType) object);
        equalsBuilder.append(this.getSource(), that.getSource());
        equalsBuilder.append(this.getRequestId(), that.getRequestId());
        equalsBuilder.append(this.getFact(), that.getFact());
    }

    public boolean equals(Object object) {
        if (!(object instanceof FactCollectionType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getSource());
        hashCodeBuilder.append(this.getRequestId());
        hashCodeBuilder.append(this.getFact());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        {
            SourceType theSource;
            theSource = this.getSource();
            toStringBuilder.append("source", theSource);
        }
        {
            Long theRequestId;
            theRequestId = this.getRequestId();
            toStringBuilder.append("requestId", theRequestId);
        }
        {
            List<JAXBElement<? extends FactType>> theFact;
            theFact = this.getFact();
            toStringBuilder.append("fact", theFact);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "ch.cern.cms.csc.cdw.data.FactCollectionType$FactCollectionTypeFactItem")
    @Table(name = "FACTCOLLECTIONTYPEFACTITEM")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class FactCollectionTypeFactItem
        implements Item<JAXBElement<? extends FactType>>
    {

        @XmlElementRef(name = "fact", namespace = "http://www.cern.ch/cms/csc/cdw/data", type = JAXBElement.class)
        protected JAXBElement<? extends FactType> item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * 
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link SlidingTmbTriggerCounterFactType }{@code >}
         *     {@link JAXBElement }{@code <}{@link CumulativeTmbTriggerCounterFactType }{@code >}
         *     {@link JAXBElement }{@code <}{@link FactType }{@code >}
         *     
         */
        @Transient
        public JAXBElement<? extends FactType> getItem() {
            return item;
        }

        /**
         * 
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link SlidingTmbTriggerCounterFactType }{@code >}
         *     {@link JAXBElement }{@code <}{@link CumulativeTmbTriggerCounterFactType }{@code >}
         *     {@link JAXBElement }{@code <}{@link FactType }{@code >}
         *     
         */
        public void setItem(JAXBElement<? extends FactType> value) {
            this.item = ((JAXBElement<? extends FactType> ) value);
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        @Basic
        @Column(name = "ITEMNAME")
        public String getItemName() {
            if (this.getItem() instanceof JAXBElement) {
                return JAXBElementUtils.getName(((JAXBElement<FactType> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemName(String target) {
            if (target!= null) {
                setItem(JAXBElementUtils.wrap(this.getItem(), target, FactType.class));
            }
        }

        @ManyToOne(targetEntity = FactType.class, cascade = {
            CascadeType.ALL
        })
        @JoinColumn(name = "ITEMVALUE_FACTCOLLECTIONTYPE_0")
        public FactType getItemValue() {
            if (this.getItem() instanceof JAXBElement) {
                return JAXBElementUtils.getValue(((JAXBElement<FactType> ) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemValue(FactType target) {
            if (target!= null) {
                setItem(JAXBElementUtils.wrap(this.getItem(), target));
            }
        }

    }

}
