#!/bin/sh










cd
. .bash_profile
. cern_oracle
delete_processes_by_name "/home/fast/pvss_fsm/smi"
delete_processes_by_name "/home/fast/pvss_fsm/bin/PVSS00"
delete_processes_by_name "PROJ\ pvss_fsm"
delete_processes_by_name "/home/fast/pvss_fsm/config/config"
#### only for pvss_fsm 
delete_processes_by_name "start_servers"
delete_processes_by_name "delete_old_lib_versions"
delete_processes_by_name "mudcsServer.ctl"
delete_processes_by_name "PVSS00ctrl -num 4 fwFsmSrvr"
delete_processes_by_name "/opt/pvss/pvss2_v3.6/bin/PVSS"
echo "PLEASE WAIT A FEW SECONDS"
echo "PLEASE WAIT A FEW SECONDS"
echo "PLEASE WAIT A FEW SECONDS"
echo "PLEASE WAIT A FEW SECONDS"
echo "PLEASE WAIT A FEW SECONDS"
echo "PLEASE WAIT A FEW SECONDS"
echo "PLEASE WAIT A FEW SECONDS"
sleep 10
#
/opt/pvss/pvss2_v3.6/bin/PVSStoolLogViewer -single -config /home/fast/pvss_fsm/config/config -lang en_US.iso88591 &
/opt/pvss/pvss2_v3.6/bin/PVSS00pmon -PROJ pvss_fsm -config /home/fast/pvss_fsm/config/config &
startPA
exit
/home/pvss/pvss2_v3.0/bin/PVSS00data -PROJ pvss_fsm -pmonIndex 1 &
/home/pvss/pvss2_v3.0/bin/PVSS00valarch -PROJ pvss_fsm -pmonIndex 2 -num 0 &
/home/pvss/pvss2_v3.0/bin/PVSS00valarch -PROJ pvss_fsm -pmonIndex 3 -num 1 &
/home/pvss/pvss2_v3.0/bin/PVSS00valarch -PROJ pvss_fsm -pmonIndex 4 -num 2 &
/home/pvss/pvss2_v3.0/bin/PVSS00valarch -PROJ pvss_fsm -pmonIndex 5 -num 3 &
/home/pvss/pvss2_v3.0/bin/PVSS00valarch -PROJ pvss_fsm -pmonIndex 6 -num 4 &
/home/pvss/pvss2_v3.0/bin/PVSS00valarch -PROJ pvss_fsm -pmonIndex 7 -num 5 &
/home/pvss/pvss2_v3.0/bin/PVSS00event -PROJ pvss_fsm -pmonIndex 8 &
/home/pvss/pvss2_v3.0/bin/PVSS00sim -PROJ pvss_fsm -pmonIndex 9 &
/home/pvss/pvss2_v3.0/bin/PVSS00ctrl -PROJ pvss_fsm -pmonIndex 10 -f pvss_scripts.lst &
/home/pvss/pvss2_v3.0/bin/PVSS00dist -PROJ pvss_fsm -pmonIndex 11 &
/home/pvss/pvss2_v3.0/bin/PVSS00ui -PROJ pvss_fsm -pmonIndex 12 -m vision -p emu/emuEmuVisualServer.pnl &
#PVSS00blink -display pcmsucr3:0.0 32 4 20 0
#PVSS00XCheck pcmsucr3:0.0 25526 100
/home/pvss/pvss2_v3.0/bin/PVSS00ui -PROJ pvss_fsm -pmonIndex 13 -m gedi &
#PVSS00blink -display pcmsucr3:0.0 32 4 20 0
#PVSS00XCheck pcmsucr3:0.0 25530 100
/home/pvss/pvss2_v3.0/bin/PVSS00ui -PROJ pvss_fsm -pmonIndex 14 -m vision &
#PVSS00blink -display pcmsucr3:0.0 32 4 20 0
#PVSS00XCheck pcmsucr3:0.0 25534 100
#/home/fast/pvss_fsm/bin/PVSS00dim -num 2 -dim_dp_config _DimClient_2 -dim_dns_node pcmsucr2
#/home/fast/pvss_fsm/bin/PVSS00dim -num 3 -dim_dp_config _DimClient_3 -dim_dns_node pcmsucr4
#/home/fast/pvss_fsm/bin/PVSS00dim -num 4 -dim_dp_config _DimClient_4 -dim_dns_node ufcmshv1
#/home/fast/pvss_fsm/bin/PVSS00dim -num 5 -dim_dp_config _DimClient_5 -dim_dns_node ufcmspc02
#sh -c start_servers &
#PVSS00ctrl -num 11 delete_old_lib_versions
#PVSS00ctrl -num 4 fwFsmSrvr
#/home/pvss/pvss2_v3.0/bin/PVSS00databg -bgSyncPipeDesc 29 -PROJ pvss_fsm






