#!/bin/bash






grep $1 */*.ctl
grep $1 */*/*.ctl
grep $1 */*/*/*.ctl
grep $1 */*/*/*/*.ctl
grep $1 */*/*/*/*/*.ctl

grep $1 */*.pnl
grep $1 */*/*.pnl
grep $1 */*/*/*.pnl
grep $1 */*/*/*/*.pnl
grep $1 */*/*/*/*/*.pnl
