DELETE FROM hvdb.TRIP_INFO;
DELETE FROM hvdb.CONFIG;
DELETE FROM hvdb.CALIBRATION;
DELETE FROM hvdb.CSC_DATA;
DELETE FROM hvdb.MAP;
DELETE FROM hvdb.MASTERDB;
DELETE FROM hvdb.RDB;
DELETE FROM hvdb.PRIME;
DELETE FROM hvdb.HVCARD;
DELETE FROM hvdb.HOST;
DELETE FROM hvdb.DNS;

