<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.cern.ch/cms/csc/exsys/wsdl" xmlns:ns="http://www.cern.ch/cms/csc/exsys" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="getEmuCounters" targetNamespace="http://www.cern.ch/cms/csc/exsys/wsdl">
<wsdl:import namespace="http://www.cern.ch/cms/csc/exsys/wsdl" location="getEmuCounters.wsdl"/>
<wsdl:binding name="getEmuCountersBinding" type="tns:getEmuCountersPortType">
<soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
<wsdl:operation name="getEmuCounters">
<soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="getEmuCounters_action"/>
<wsdl:input name="input1">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http://www.cern.ch/cms/csc/exsys/wsdl" use="literal"/>
</wsdl:input>
<wsdl:output name="output1">
<soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" namespace="http://www.cern.ch/cms/csc/exsys/wsdl" use="literal"/>
</wsdl:output>
<wsdl:fault name="fault1">
<soap:fault xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="fault1" use="literal"/>
</wsdl:fault>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="getEmuCountersService">
<wsdl:port name="getEmuCountersPort" binding="tns:getEmuCountersBinding">
<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="REPLACE_WITH_ACTUAL_URL"/>
</wsdl:port>
</wsdl:service>
</definitions>
