#!/bin/bash







#CSC_DIR_REP=/home/fast/pvss_fsm/scripts/libs/emu*.ctl
#CSC_DIR_REP=/home/fast/pvss_fsm/scripts/libs/fw*
#CSC_DIR_REP=/home/fast/pvss_fsm/scripts/libs/fw*/fw*.ctl

#CSC_DIR_REP=/home/fast/pvss_fsm/scripts/mudcs*.ctl

#------------------

PROJECT='/home/fast/pvss_fsm_devSnmp/panels/CMS_CSCfw_HV_CC/'
#PROJECT=$PROJECT'emuDiskHVmaster.pnl'
#echo $PROJECT

#echo $PROJECT'*_removed111'

#exit

cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_2.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_3.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_4.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_5.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_6.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_7.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_8.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_9.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_10.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_11.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_12.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_13.pnl'
cp $PROJECT'emuDiskHVmaster.pnl' $PROJECT'emuDiskHVmaster_14.pnl'


#cp /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster.pnl /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_3.pnl
#cp /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster.pnl /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_4.pnl
#cp /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster.pnl /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_5.pnl
#cp /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster.pnl /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_6.pnl
#cp /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster.pnl /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_7.pnl
#cp /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster.pnl /home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl


##CSC_DIR_REP=/home/fast/pvss_fsm/panels/*.pnl
##CSC_DIR_REP=/home/fast/pvss_fsm/panels/emu/*.pnl
###CSC_DIR_REP=/home/fast/pvss_fsm/panels/emu/*master_*.pnl


function fun1(){

##echo -n CSC_fwG_ > rep;
echo -n $VALUE_DEL > del;
echo -n $VALUE_REP > rep;
file_editing_samplefilelist $PANEL del rep > temp
}




####./file_editing_samplefilelist test1/test2/test3/*.ctl del rep > temp

#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_2.pnl
PANEL=$PROJECT'emuDiskHVmaster_2.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_2
fun1

VALUE_DEL=id_1
VALUE_REP=id_2
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_2
fun1
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_3.pnl
PANEL=$PROJECT'emuDiskHVmaster_3.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_3
fun1

VALUE_DEL=id_1
VALUE_REP=id_3
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_3
fun1
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_4.pnl
PANEL=$PROJECT'emuDiskHVmaster_4.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_4
fun1

VALUE_DEL=id_1
VALUE_REP=id_4
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_4
fun1
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_5.pnl
PANEL=$PROJECT'emuDiskHVmaster_5.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_5
fun1

VALUE_DEL=id_1
VALUE_REP=id_5
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_5
fun1
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_6.pnl
PANEL=$PROJECT'emuDiskHVmaster_6.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_6
fun1

VALUE_DEL=id_1
VALUE_REP=id_6
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_6
fun1
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_7.pnl
PANEL=$PROJECT'emuDiskHVmaster_7.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_7
fun1

VALUE_DEL=id_1
VALUE_REP=id_7
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_7
fun1
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_8.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_8
fun1

VALUE_DEL=id_1
VALUE_REP=id_8
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_8
fun1
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_9.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_9
fun1

VALUE_DEL=id_1
VALUE_REP=id_9
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_9
fun1
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_10.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_10
fun1

VALUE_DEL=id_1
VALUE_REP=id_10
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_10
fun1
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_11.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_11
fun1

VALUE_DEL=id_1
VALUE_REP=id_11
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_11
fun1
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_12.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_12
fun1

VALUE_DEL=id_1
VALUE_REP=id_12
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_12
fun1
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_13.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_13
fun1

VALUE_DEL=id_1
VALUE_REP=id_13
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_13
fun1
#--------------------------------------------------------------------------
#--------------------------------------------------------------------------
#PANEL=/home/fast/pvss_fsm/panels/emu/emuDiskHVmaster_8.pnl
PANEL=$PROJECT'emuDiskHVmaster_14.pnl'
VALUE_DEL=table_ms_1
VALUE_REP=table_ms_14
fun1

VALUE_DEL=id_1
VALUE_REP=id_14
fun1

VALUE_DEL=update_time_1
VALUE_REP=update_time_14
fun1
#--------------------------------------------------------------------------


PROJECT1=$PROJECT'*_removed111'
rm -fv $PROJECT1
