package org.cern.cms.csc.dw.metadata;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.cern.cms.csc.dw.util.ClassUtil;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.persistence.Entity;
import org.cern.cms.csc.dw.model.annotation.FactAnn;
import org.cern.cms.csc.dw.model.fact.Fact;

@SuppressWarnings("unchecked")
public class MetadataManager {

    private static final String FACTS_PACKAGE = "org.cern.cms.csc.dw.model.fact";
    private static final String FACTS_RESOURCE = "/org/cern/cms/csc/dw/metadata/facts.properties";

    private static Map<Class, FactMd> factClasses = null;

    public MetadataManager() {
        if (factClasses == null) {
            factClasses = new HashMap<Class, FactMd>();
            FileReader fr = null;
            try {
                Properties p = new Properties();
                InputStream in = MetadataManager.class.getResourceAsStream(FACTS_RESOURCE);
                if (in != null) {
                    p.load(in);
                    for (Object key: p.keySet()) {
                        String className = p.getProperty((String) key);
                        Class c = MetadataManager.class.getClassLoader().loadClass(className);
                        factClasses.put(c, new FactMd(c));
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(MetadataManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public final Collection<FactMd> getFactMDs() {
        return Collections.unmodifiableCollection(factClasses.values());
    }

    public final FactMd getFactMd(Class clazz) {
        return factClasses.get(clazz);
    }

    public static void main(String[] args) {

        try {
            
            if (args.length < 1) {
                throw new IllegalArgumentException("Please supply base directory to store property file");
            }

            String baseDir = args[0];
            String factsFile = baseDir + FACTS_RESOURCE;

            Properties p = new Properties();
            for (Class c : ClassUtil.packageClassses(FACTS_PACKAGE)) {
                if (c.getSuperclass() != null) {
                    if (c.getSuperclass().equals(Fact.class) && c.isAnnotationPresent(Entity.class) && c.isAnnotationPresent(FactAnn.class)) {
                        p.setProperty(c.getSimpleName(), c.getName());
                    }
                }
            }
            File f = new File(factsFile);
            FileWriter fw = new FileWriter(f);
            p.store(fw, "Fact Classes\nGenerated by " + MetadataManager.class.getName());

            System.out.print(MetadataManager.class.getSimpleName());
            System.out.println(": " + String.valueOf(p.size()) + " Fact classes found and saved to " + factsFile);

        } catch (IOException ex) {
            Logger.getLogger(MetadataManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
