//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.dw.model.fact;

import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cern.cms.csc.dw.model.annotation.FactAnn;
import org.cern.cms.csc.dw.model.annotation.OlapDimension;


/**
 * <p>Java class for tmbCounterFactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tmbCounterFactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.cern.ch/cms/csc/dw/model}factType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descriptions" type="{http://www.cern.ch/cms/csc/dw/model/dse}tmbCounterDescriptionDSEType" minOccurs="0"/>
 *         &lt;element name="tc00" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc01" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc02" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc03" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc04" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc05" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc06" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc07" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc08" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc09" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc10" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc11" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc12" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc13" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc14" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc15" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc16" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc17" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc18" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc19" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc20" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc21" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc22" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc23" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc24" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc25" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc26" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc27" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc28" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc29" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc30" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc31" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc32" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc33" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc34" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc35" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc36" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc37" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc38" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc39" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc40" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc41" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc42" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc43" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc44" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc45" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc46" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc47" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc48" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc49" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc50" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc51" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc52" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc53" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc54" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc55" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc56" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc57" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc58" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc59" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc60" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc61" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc62" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc63" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc64" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc65" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc66" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc67" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc68" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc69" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc70" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc71" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc72" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc73" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc74" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc75" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc76" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc77" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc78" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc79" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc80" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc81" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc82" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc83" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc84" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc85" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc86" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc87" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc88" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc89" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc90" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc91" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc92" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc93" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc94" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc95" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc96" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc97" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc98" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tc99" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tmbCounterFactType", propOrder = {
    "version",
    "descriptions",
    "tc00",
    "tc01",
    "tc02",
    "tc03",
    "tc04",
    "tc05",
    "tc06",
    "tc07",
    "tc08",
    "tc09",
    "tc10",
    "tc11",
    "tc12",
    "tc13",
    "tc14",
    "tc15",
    "tc16",
    "tc17",
    "tc18",
    "tc19",
    "tc20",
    "tc21",
    "tc22",
    "tc23",
    "tc24",
    "tc25",
    "tc26",
    "tc27",
    "tc28",
    "tc29",
    "tc30",
    "tc31",
    "tc32",
    "tc33",
    "tc34",
    "tc35",
    "tc36",
    "tc37",
    "tc38",
    "tc39",
    "tc40",
    "tc41",
    "tc42",
    "tc43",
    "tc44",
    "tc45",
    "tc46",
    "tc47",
    "tc48",
    "tc49",
    "tc50",
    "tc51",
    "tc52",
    "tc53",
    "tc54",
    "tc55",
    "tc56",
    "tc57",
    "tc58",
    "tc59",
    "tc60",
    "tc61",
    "tc62",
    "tc63",
    "tc64",
    "tc65",
    "tc66",
    "tc67",
    "tc68",
    "tc69",
    "tc70",
    "tc71",
    "tc72",
    "tc73",
    "tc74",
    "tc75",
    "tc76",
    "tc77",
    "tc78",
    "tc79",
    "tc80",
    "tc81",
    "tc82",
    "tc83",
    "tc84",
    "tc85",
    "tc86",
    "tc87",
    "tc88",
    "tc89",
    "tc90",
    "tc91",
    "tc92",
    "tc93",
    "tc94",
    "tc95",
    "tc96",
    "tc97",
    "tc98",
    "tc99"
})
@Entity(name = "org.cern.cms.csc.dw.model.fact.TmbCounterFact")
@Table(name = "CDW_TMB_CNT_FACTS")
@FactAnn(limitComponents = {
    "TMB"
}, title = "TMB Counters")
public class TmbCounterFact
    extends Fact
    implements Serializable
{

    @XmlElement(required = true)
    protected String version;
    protected org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE descriptions;
    @XmlElement(required = true)
    protected BigInteger tc00;
    @XmlElement(required = true)
    protected BigInteger tc01;
    @XmlElement(required = true)
    protected BigInteger tc02;
    @XmlElement(required = true)
    protected BigInteger tc03;
    @XmlElement(required = true)
    protected BigInteger tc04;
    @XmlElement(required = true)
    protected BigInteger tc05;
    @XmlElement(required = true)
    protected BigInteger tc06;
    @XmlElement(required = true)
    protected BigInteger tc07;
    @XmlElement(required = true)
    protected BigInteger tc08;
    @XmlElement(required = true)
    protected BigInteger tc09;
    @XmlElement(required = true)
    protected BigInteger tc10;
    @XmlElement(required = true)
    protected BigInteger tc11;
    @XmlElement(required = true)
    protected BigInteger tc12;
    @XmlElement(required = true)
    protected BigInteger tc13;
    @XmlElement(required = true)
    protected BigInteger tc14;
    @XmlElement(required = true)
    protected BigInteger tc15;
    @XmlElement(required = true)
    protected BigInteger tc16;
    @XmlElement(required = true)
    protected BigInteger tc17;
    @XmlElement(required = true)
    protected BigInteger tc18;
    @XmlElement(required = true)
    protected BigInteger tc19;
    @XmlElement(required = true)
    protected BigInteger tc20;
    @XmlElement(required = true)
    protected BigInteger tc21;
    @XmlElement(required = true)
    protected BigInteger tc22;
    @XmlElement(required = true)
    protected BigInteger tc23;
    @XmlElement(required = true)
    protected BigInteger tc24;
    @XmlElement(required = true)
    protected BigInteger tc25;
    @XmlElement(required = true)
    protected BigInteger tc26;
    @XmlElement(required = true)
    protected BigInteger tc27;
    @XmlElement(required = true)
    protected BigInteger tc28;
    @XmlElement(required = true)
    protected BigInteger tc29;
    @XmlElement(required = true)
    protected BigInteger tc30;
    @XmlElement(required = true)
    protected BigInteger tc31;
    @XmlElement(required = true)
    protected BigInteger tc32;
    @XmlElement(required = true)
    protected BigInteger tc33;
    @XmlElement(required = true)
    protected BigInteger tc34;
    @XmlElement(required = true)
    protected BigInteger tc35;
    @XmlElement(required = true)
    protected BigInteger tc36;
    @XmlElement(required = true)
    protected BigInteger tc37;
    @XmlElement(required = true)
    protected BigInteger tc38;
    @XmlElement(required = true)
    protected BigInteger tc39;
    @XmlElement(required = true)
    protected BigInteger tc40;
    @XmlElement(required = true)
    protected BigInteger tc41;
    @XmlElement(required = true)
    protected BigInteger tc42;
    @XmlElement(required = true)
    protected BigInteger tc43;
    @XmlElement(required = true)
    protected BigInteger tc44;
    @XmlElement(required = true)
    protected BigInteger tc45;
    @XmlElement(required = true)
    protected BigInteger tc46;
    @XmlElement(required = true)
    protected BigInteger tc47;
    @XmlElement(required = true)
    protected BigInteger tc48;
    @XmlElement(required = true)
    protected BigInteger tc49;
    @XmlElement(required = true)
    protected BigInteger tc50;
    @XmlElement(required = true)
    protected BigInteger tc51;
    @XmlElement(required = true)
    protected BigInteger tc52;
    @XmlElement(required = true)
    protected BigInteger tc53;
    @XmlElement(required = true)
    protected BigInteger tc54;
    @XmlElement(required = true)
    protected BigInteger tc55;
    @XmlElement(required = true)
    protected BigInteger tc56;
    @XmlElement(required = true)
    protected BigInteger tc57;
    @XmlElement(required = true)
    protected BigInteger tc58;
    @XmlElement(required = true)
    protected BigInteger tc59;
    @XmlElement(required = true)
    protected BigInteger tc60;
    @XmlElement(required = true)
    protected BigInteger tc61;
    @XmlElement(required = true)
    protected BigInteger tc62;
    @XmlElement(required = true)
    protected BigInteger tc63;
    @XmlElement(required = true)
    protected BigInteger tc64;
    @XmlElement(required = true)
    protected BigInteger tc65;
    @XmlElement(required = true)
    protected BigInteger tc66;
    @XmlElement(required = true)
    protected BigInteger tc67;
    @XmlElement(required = true)
    protected BigInteger tc68;
    @XmlElement(required = true)
    protected BigInteger tc69;
    @XmlElement(required = true)
    protected BigInteger tc70;
    @XmlElement(required = true)
    protected BigInteger tc71;
    @XmlElement(required = true)
    protected BigInteger tc72;
    @XmlElement(required = true)
    protected BigInteger tc73;
    @XmlElement(required = true)
    protected BigInteger tc74;
    @XmlElement(required = true)
    protected BigInteger tc75;
    @XmlElement(required = true)
    protected BigInteger tc76;
    @XmlElement(required = true)
    protected BigInteger tc77;
    @XmlElement(required = true)
    protected BigInteger tc78;
    @XmlElement(required = true)
    protected BigInteger tc79;
    @XmlElement(required = true)
    protected BigInteger tc80;
    @XmlElement(required = true)
    protected BigInteger tc81;
    @XmlElement(required = true)
    protected BigInteger tc82;
    @XmlElement(required = true)
    protected BigInteger tc83;
    @XmlElement(required = true)
    protected BigInteger tc84;
    @XmlElement(required = true)
    protected BigInteger tc85;
    @XmlElement(required = true)
    protected BigInteger tc86;
    @XmlElement(required = true)
    protected BigInteger tc87;
    @XmlElement(required = true)
    protected BigInteger tc88;
    @XmlElement(required = true)
    protected BigInteger tc89;
    @XmlElement(required = true)
    protected BigInteger tc90;
    @XmlElement(required = true)
    protected BigInteger tc91;
    @XmlElement(required = true)
    protected BigInteger tc92;
    @XmlElement(required = true)
    protected BigInteger tc93;
    @XmlElement(required = true)
    protected BigInteger tc94;
    @XmlElement(required = true)
    protected BigInteger tc95;
    @XmlElement(required = true)
    protected BigInteger tc96;
    @XmlElement(required = true)
    protected BigInteger tc97;
    @XmlElement(required = true)
    protected BigInteger tc98;
    @XmlElement(required = true)
    protected BigInteger tc99;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FCT_VERSION", length = 4)
    @OlapDimension(name = "version")
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    @Transient
    public boolean isSetVersion() {
        return (this.version!= null);
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE }
     *     
     */
    @ManyToOne(targetEntity = org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "FCT_DESCRIPTIONS")
    public org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE }
     *     
     */
    public void setDescriptions(org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE value) {
        this.descriptions = value;
    }

    @Transient
    public boolean isSetDescriptions() {
        return (this.descriptions!= null);
    }

    /**
     * Gets the value of the tc00 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC00", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC00")
    public BigInteger getTc00() {
        return tc00;
    }

    /**
     * Sets the value of the tc00 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc00(BigInteger value) {
        this.tc00 = value;
    }

    @Transient
    public boolean isSetTc00() {
        return (this.tc00 != null);
    }

    /**
     * Gets the value of the tc01 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC01", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC01")
    public BigInteger getTc01() {
        return tc01;
    }

    /**
     * Sets the value of the tc01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc01(BigInteger value) {
        this.tc01 = value;
    }

    @Transient
    public boolean isSetTc01() {
        return (this.tc01 != null);
    }

    /**
     * Gets the value of the tc02 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC02", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC02")
    public BigInteger getTc02() {
        return tc02;
    }

    /**
     * Sets the value of the tc02 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc02(BigInteger value) {
        this.tc02 = value;
    }

    @Transient
    public boolean isSetTc02() {
        return (this.tc02 != null);
    }

    /**
     * Gets the value of the tc03 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC03", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC03")
    public BigInteger getTc03() {
        return tc03;
    }

    /**
     * Sets the value of the tc03 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc03(BigInteger value) {
        this.tc03 = value;
    }

    @Transient
    public boolean isSetTc03() {
        return (this.tc03 != null);
    }

    /**
     * Gets the value of the tc04 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC04", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC04")
    public BigInteger getTc04() {
        return tc04;
    }

    /**
     * Sets the value of the tc04 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc04(BigInteger value) {
        this.tc04 = value;
    }

    @Transient
    public boolean isSetTc04() {
        return (this.tc04 != null);
    }

    /**
     * Gets the value of the tc05 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC05", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC05")
    public BigInteger getTc05() {
        return tc05;
    }

    /**
     * Sets the value of the tc05 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc05(BigInteger value) {
        this.tc05 = value;
    }

    @Transient
    public boolean isSetTc05() {
        return (this.tc05 != null);
    }

    /**
     * Gets the value of the tc06 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC06", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC06")
    public BigInteger getTc06() {
        return tc06;
    }

    /**
     * Sets the value of the tc06 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc06(BigInteger value) {
        this.tc06 = value;
    }

    @Transient
    public boolean isSetTc06() {
        return (this.tc06 != null);
    }

    /**
     * Gets the value of the tc07 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC07", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC07")
    public BigInteger getTc07() {
        return tc07;
    }

    /**
     * Sets the value of the tc07 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc07(BigInteger value) {
        this.tc07 = value;
    }

    @Transient
    public boolean isSetTc07() {
        return (this.tc07 != null);
    }

    /**
     * Gets the value of the tc08 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC08", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC08")
    public BigInteger getTc08() {
        return tc08;
    }

    /**
     * Sets the value of the tc08 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc08(BigInteger value) {
        this.tc08 = value;
    }

    @Transient
    public boolean isSetTc08() {
        return (this.tc08 != null);
    }

    /**
     * Gets the value of the tc09 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC09", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC09")
    public BigInteger getTc09() {
        return tc09;
    }

    /**
     * Sets the value of the tc09 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc09(BigInteger value) {
        this.tc09 = value;
    }

    @Transient
    public boolean isSetTc09() {
        return (this.tc09 != null);
    }

    /**
     * Gets the value of the tc10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC10", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC10")
    public BigInteger getTc10() {
        return tc10;
    }

    /**
     * Sets the value of the tc10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc10(BigInteger value) {
        this.tc10 = value;
    }

    @Transient
    public boolean isSetTc10() {
        return (this.tc10 != null);
    }

    /**
     * Gets the value of the tc11 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC11", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC11")
    public BigInteger getTc11() {
        return tc11;
    }

    /**
     * Sets the value of the tc11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc11(BigInteger value) {
        this.tc11 = value;
    }

    @Transient
    public boolean isSetTc11() {
        return (this.tc11 != null);
    }

    /**
     * Gets the value of the tc12 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC12", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC12")
    public BigInteger getTc12() {
        return tc12;
    }

    /**
     * Sets the value of the tc12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc12(BigInteger value) {
        this.tc12 = value;
    }

    @Transient
    public boolean isSetTc12() {
        return (this.tc12 != null);
    }

    /**
     * Gets the value of the tc13 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC13", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC13")
    public BigInteger getTc13() {
        return tc13;
    }

    /**
     * Sets the value of the tc13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc13(BigInteger value) {
        this.tc13 = value;
    }

    @Transient
    public boolean isSetTc13() {
        return (this.tc13 != null);
    }

    /**
     * Gets the value of the tc14 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC14", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC14")
    public BigInteger getTc14() {
        return tc14;
    }

    /**
     * Sets the value of the tc14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc14(BigInteger value) {
        this.tc14 = value;
    }

    @Transient
    public boolean isSetTc14() {
        return (this.tc14 != null);
    }

    /**
     * Gets the value of the tc15 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC15", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC15")
    public BigInteger getTc15() {
        return tc15;
    }

    /**
     * Sets the value of the tc15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc15(BigInteger value) {
        this.tc15 = value;
    }

    @Transient
    public boolean isSetTc15() {
        return (this.tc15 != null);
    }

    /**
     * Gets the value of the tc16 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC16", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC16")
    public BigInteger getTc16() {
        return tc16;
    }

    /**
     * Sets the value of the tc16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc16(BigInteger value) {
        this.tc16 = value;
    }

    @Transient
    public boolean isSetTc16() {
        return (this.tc16 != null);
    }

    /**
     * Gets the value of the tc17 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC17", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC17")
    public BigInteger getTc17() {
        return tc17;
    }

    /**
     * Sets the value of the tc17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc17(BigInteger value) {
        this.tc17 = value;
    }

    @Transient
    public boolean isSetTc17() {
        return (this.tc17 != null);
    }

    /**
     * Gets the value of the tc18 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC18", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC18")
    public BigInteger getTc18() {
        return tc18;
    }

    /**
     * Sets the value of the tc18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc18(BigInteger value) {
        this.tc18 = value;
    }

    @Transient
    public boolean isSetTc18() {
        return (this.tc18 != null);
    }

    /**
     * Gets the value of the tc19 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC19", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC19")
    public BigInteger getTc19() {
        return tc19;
    }

    /**
     * Sets the value of the tc19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc19(BigInteger value) {
        this.tc19 = value;
    }

    @Transient
    public boolean isSetTc19() {
        return (this.tc19 != null);
    }

    /**
     * Gets the value of the tc20 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC20", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC20")
    public BigInteger getTc20() {
        return tc20;
    }

    /**
     * Sets the value of the tc20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc20(BigInteger value) {
        this.tc20 = value;
    }

    @Transient
    public boolean isSetTc20() {
        return (this.tc20 != null);
    }

    /**
     * Gets the value of the tc21 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC21", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC21")
    public BigInteger getTc21() {
        return tc21;
    }

    /**
     * Sets the value of the tc21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc21(BigInteger value) {
        this.tc21 = value;
    }

    @Transient
    public boolean isSetTc21() {
        return (this.tc21 != null);
    }

    /**
     * Gets the value of the tc22 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC22", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC22")
    public BigInteger getTc22() {
        return tc22;
    }

    /**
     * Sets the value of the tc22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc22(BigInteger value) {
        this.tc22 = value;
    }

    @Transient
    public boolean isSetTc22() {
        return (this.tc22 != null);
    }

    /**
     * Gets the value of the tc23 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC23", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC23")
    public BigInteger getTc23() {
        return tc23;
    }

    /**
     * Sets the value of the tc23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc23(BigInteger value) {
        this.tc23 = value;
    }

    @Transient
    public boolean isSetTc23() {
        return (this.tc23 != null);
    }

    /**
     * Gets the value of the tc24 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC24", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC24")
    public BigInteger getTc24() {
        return tc24;
    }

    /**
     * Sets the value of the tc24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc24(BigInteger value) {
        this.tc24 = value;
    }

    @Transient
    public boolean isSetTc24() {
        return (this.tc24 != null);
    }

    /**
     * Gets the value of the tc25 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC25", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC25")
    public BigInteger getTc25() {
        return tc25;
    }

    /**
     * Sets the value of the tc25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc25(BigInteger value) {
        this.tc25 = value;
    }

    @Transient
    public boolean isSetTc25() {
        return (this.tc25 != null);
    }

    /**
     * Gets the value of the tc26 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC26", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC26")
    public BigInteger getTc26() {
        return tc26;
    }

    /**
     * Sets the value of the tc26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc26(BigInteger value) {
        this.tc26 = value;
    }

    @Transient
    public boolean isSetTc26() {
        return (this.tc26 != null);
    }

    /**
     * Gets the value of the tc27 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC27", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC27")
    public BigInteger getTc27() {
        return tc27;
    }

    /**
     * Sets the value of the tc27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc27(BigInteger value) {
        this.tc27 = value;
    }

    @Transient
    public boolean isSetTc27() {
        return (this.tc27 != null);
    }

    /**
     * Gets the value of the tc28 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC28", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC28")
    public BigInteger getTc28() {
        return tc28;
    }

    /**
     * Sets the value of the tc28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc28(BigInteger value) {
        this.tc28 = value;
    }

    @Transient
    public boolean isSetTc28() {
        return (this.tc28 != null);
    }

    /**
     * Gets the value of the tc29 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC29", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC29")
    public BigInteger getTc29() {
        return tc29;
    }

    /**
     * Sets the value of the tc29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc29(BigInteger value) {
        this.tc29 = value;
    }

    @Transient
    public boolean isSetTc29() {
        return (this.tc29 != null);
    }

    /**
     * Gets the value of the tc30 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC30", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC30")
    public BigInteger getTc30() {
        return tc30;
    }

    /**
     * Sets the value of the tc30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc30(BigInteger value) {
        this.tc30 = value;
    }

    @Transient
    public boolean isSetTc30() {
        return (this.tc30 != null);
    }

    /**
     * Gets the value of the tc31 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC31", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC31")
    public BigInteger getTc31() {
        return tc31;
    }

    /**
     * Sets the value of the tc31 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc31(BigInteger value) {
        this.tc31 = value;
    }

    @Transient
    public boolean isSetTc31() {
        return (this.tc31 != null);
    }

    /**
     * Gets the value of the tc32 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC32", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC32")
    public BigInteger getTc32() {
        return tc32;
    }

    /**
     * Sets the value of the tc32 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc32(BigInteger value) {
        this.tc32 = value;
    }

    @Transient
    public boolean isSetTc32() {
        return (this.tc32 != null);
    }

    /**
     * Gets the value of the tc33 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC33", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC33")
    public BigInteger getTc33() {
        return tc33;
    }

    /**
     * Sets the value of the tc33 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc33(BigInteger value) {
        this.tc33 = value;
    }

    @Transient
    public boolean isSetTc33() {
        return (this.tc33 != null);
    }

    /**
     * Gets the value of the tc34 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC34", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC34")
    public BigInteger getTc34() {
        return tc34;
    }

    /**
     * Sets the value of the tc34 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc34(BigInteger value) {
        this.tc34 = value;
    }

    @Transient
    public boolean isSetTc34() {
        return (this.tc34 != null);
    }

    /**
     * Gets the value of the tc35 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC35", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC35")
    public BigInteger getTc35() {
        return tc35;
    }

    /**
     * Sets the value of the tc35 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc35(BigInteger value) {
        this.tc35 = value;
    }

    @Transient
    public boolean isSetTc35() {
        return (this.tc35 != null);
    }

    /**
     * Gets the value of the tc36 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC36", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC36")
    public BigInteger getTc36() {
        return tc36;
    }

    /**
     * Sets the value of the tc36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc36(BigInteger value) {
        this.tc36 = value;
    }

    @Transient
    public boolean isSetTc36() {
        return (this.tc36 != null);
    }

    /**
     * Gets the value of the tc37 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC37", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC37")
    public BigInteger getTc37() {
        return tc37;
    }

    /**
     * Sets the value of the tc37 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc37(BigInteger value) {
        this.tc37 = value;
    }

    @Transient
    public boolean isSetTc37() {
        return (this.tc37 != null);
    }

    /**
     * Gets the value of the tc38 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC38", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC38")
    public BigInteger getTc38() {
        return tc38;
    }

    /**
     * Sets the value of the tc38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc38(BigInteger value) {
        this.tc38 = value;
    }

    @Transient
    public boolean isSetTc38() {
        return (this.tc38 != null);
    }

    /**
     * Gets the value of the tc39 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC39", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC39")
    public BigInteger getTc39() {
        return tc39;
    }

    /**
     * Sets the value of the tc39 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc39(BigInteger value) {
        this.tc39 = value;
    }

    @Transient
    public boolean isSetTc39() {
        return (this.tc39 != null);
    }

    /**
     * Gets the value of the tc40 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC40", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC40")
    public BigInteger getTc40() {
        return tc40;
    }

    /**
     * Sets the value of the tc40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc40(BigInteger value) {
        this.tc40 = value;
    }

    @Transient
    public boolean isSetTc40() {
        return (this.tc40 != null);
    }

    /**
     * Gets the value of the tc41 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC41", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC41")
    public BigInteger getTc41() {
        return tc41;
    }

    /**
     * Sets the value of the tc41 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc41(BigInteger value) {
        this.tc41 = value;
    }

    @Transient
    public boolean isSetTc41() {
        return (this.tc41 != null);
    }

    /**
     * Gets the value of the tc42 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC42", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC42")
    public BigInteger getTc42() {
        return tc42;
    }

    /**
     * Sets the value of the tc42 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc42(BigInteger value) {
        this.tc42 = value;
    }

    @Transient
    public boolean isSetTc42() {
        return (this.tc42 != null);
    }

    /**
     * Gets the value of the tc43 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC43", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC43")
    public BigInteger getTc43() {
        return tc43;
    }

    /**
     * Sets the value of the tc43 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc43(BigInteger value) {
        this.tc43 = value;
    }

    @Transient
    public boolean isSetTc43() {
        return (this.tc43 != null);
    }

    /**
     * Gets the value of the tc44 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC44", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC44")
    public BigInteger getTc44() {
        return tc44;
    }

    /**
     * Sets the value of the tc44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc44(BigInteger value) {
        this.tc44 = value;
    }

    @Transient
    public boolean isSetTc44() {
        return (this.tc44 != null);
    }

    /**
     * Gets the value of the tc45 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC45", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC45")
    public BigInteger getTc45() {
        return tc45;
    }

    /**
     * Sets the value of the tc45 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc45(BigInteger value) {
        this.tc45 = value;
    }

    @Transient
    public boolean isSetTc45() {
        return (this.tc45 != null);
    }

    /**
     * Gets the value of the tc46 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC46", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC46")
    public BigInteger getTc46() {
        return tc46;
    }

    /**
     * Sets the value of the tc46 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc46(BigInteger value) {
        this.tc46 = value;
    }

    @Transient
    public boolean isSetTc46() {
        return (this.tc46 != null);
    }

    /**
     * Gets the value of the tc47 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC47", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC47")
    public BigInteger getTc47() {
        return tc47;
    }

    /**
     * Sets the value of the tc47 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc47(BigInteger value) {
        this.tc47 = value;
    }

    @Transient
    public boolean isSetTc47() {
        return (this.tc47 != null);
    }

    /**
     * Gets the value of the tc48 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC48", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC48")
    public BigInteger getTc48() {
        return tc48;
    }

    /**
     * Sets the value of the tc48 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc48(BigInteger value) {
        this.tc48 = value;
    }

    @Transient
    public boolean isSetTc48() {
        return (this.tc48 != null);
    }

    /**
     * Gets the value of the tc49 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC49", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC49")
    public BigInteger getTc49() {
        return tc49;
    }

    /**
     * Sets the value of the tc49 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc49(BigInteger value) {
        this.tc49 = value;
    }

    @Transient
    public boolean isSetTc49() {
        return (this.tc49 != null);
    }

    /**
     * Gets the value of the tc50 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC50", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC50")
    public BigInteger getTc50() {
        return tc50;
    }

    /**
     * Sets the value of the tc50 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc50(BigInteger value) {
        this.tc50 = value;
    }

    @Transient
    public boolean isSetTc50() {
        return (this.tc50 != null);
    }

    /**
     * Gets the value of the tc51 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC51", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC51")
    public BigInteger getTc51() {
        return tc51;
    }

    /**
     * Sets the value of the tc51 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc51(BigInteger value) {
        this.tc51 = value;
    }

    @Transient
    public boolean isSetTc51() {
        return (this.tc51 != null);
    }

    /**
     * Gets the value of the tc52 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC52", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC52")
    public BigInteger getTc52() {
        return tc52;
    }

    /**
     * Sets the value of the tc52 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc52(BigInteger value) {
        this.tc52 = value;
    }

    @Transient
    public boolean isSetTc52() {
        return (this.tc52 != null);
    }

    /**
     * Gets the value of the tc53 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC53", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC53")
    public BigInteger getTc53() {
        return tc53;
    }

    /**
     * Sets the value of the tc53 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc53(BigInteger value) {
        this.tc53 = value;
    }

    @Transient
    public boolean isSetTc53() {
        return (this.tc53 != null);
    }

    /**
     * Gets the value of the tc54 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC54", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC54")
    public BigInteger getTc54() {
        return tc54;
    }

    /**
     * Sets the value of the tc54 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc54(BigInteger value) {
        this.tc54 = value;
    }

    @Transient
    public boolean isSetTc54() {
        return (this.tc54 != null);
    }

    /**
     * Gets the value of the tc55 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC55", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC55")
    public BigInteger getTc55() {
        return tc55;
    }

    /**
     * Sets the value of the tc55 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc55(BigInteger value) {
        this.tc55 = value;
    }

    @Transient
    public boolean isSetTc55() {
        return (this.tc55 != null);
    }

    /**
     * Gets the value of the tc56 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC56", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC56")
    public BigInteger getTc56() {
        return tc56;
    }

    /**
     * Sets the value of the tc56 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc56(BigInteger value) {
        this.tc56 = value;
    }

    @Transient
    public boolean isSetTc56() {
        return (this.tc56 != null);
    }

    /**
     * Gets the value of the tc57 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC57", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC57")
    public BigInteger getTc57() {
        return tc57;
    }

    /**
     * Sets the value of the tc57 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc57(BigInteger value) {
        this.tc57 = value;
    }

    @Transient
    public boolean isSetTc57() {
        return (this.tc57 != null);
    }

    /**
     * Gets the value of the tc58 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC58", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC58")
    public BigInteger getTc58() {
        return tc58;
    }

    /**
     * Sets the value of the tc58 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc58(BigInteger value) {
        this.tc58 = value;
    }

    @Transient
    public boolean isSetTc58() {
        return (this.tc58 != null);
    }

    /**
     * Gets the value of the tc59 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC59", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC59")
    public BigInteger getTc59() {
        return tc59;
    }

    /**
     * Sets the value of the tc59 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc59(BigInteger value) {
        this.tc59 = value;
    }

    @Transient
    public boolean isSetTc59() {
        return (this.tc59 != null);
    }

    /**
     * Gets the value of the tc60 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC60", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC60")
    public BigInteger getTc60() {
        return tc60;
    }

    /**
     * Sets the value of the tc60 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc60(BigInteger value) {
        this.tc60 = value;
    }

    @Transient
    public boolean isSetTc60() {
        return (this.tc60 != null);
    }

    /**
     * Gets the value of the tc61 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC61", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC61")
    public BigInteger getTc61() {
        return tc61;
    }

    /**
     * Sets the value of the tc61 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc61(BigInteger value) {
        this.tc61 = value;
    }

    @Transient
    public boolean isSetTc61() {
        return (this.tc61 != null);
    }

    /**
     * Gets the value of the tc62 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC62", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC62")
    public BigInteger getTc62() {
        return tc62;
    }

    /**
     * Sets the value of the tc62 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc62(BigInteger value) {
        this.tc62 = value;
    }

    @Transient
    public boolean isSetTc62() {
        return (this.tc62 != null);
    }

    /**
     * Gets the value of the tc63 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC63", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC63")
    public BigInteger getTc63() {
        return tc63;
    }

    /**
     * Sets the value of the tc63 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc63(BigInteger value) {
        this.tc63 = value;
    }

    @Transient
    public boolean isSetTc63() {
        return (this.tc63 != null);
    }

    /**
     * Gets the value of the tc64 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC64", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC64")
    public BigInteger getTc64() {
        return tc64;
    }

    /**
     * Sets the value of the tc64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc64(BigInteger value) {
        this.tc64 = value;
    }

    @Transient
    public boolean isSetTc64() {
        return (this.tc64 != null);
    }

    /**
     * Gets the value of the tc65 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC65", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC65")
    public BigInteger getTc65() {
        return tc65;
    }

    /**
     * Sets the value of the tc65 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc65(BigInteger value) {
        this.tc65 = value;
    }

    @Transient
    public boolean isSetTc65() {
        return (this.tc65 != null);
    }

    /**
     * Gets the value of the tc66 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC66", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC66")
    public BigInteger getTc66() {
        return tc66;
    }

    /**
     * Sets the value of the tc66 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc66(BigInteger value) {
        this.tc66 = value;
    }

    @Transient
    public boolean isSetTc66() {
        return (this.tc66 != null);
    }

    /**
     * Gets the value of the tc67 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC67", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC67")
    public BigInteger getTc67() {
        return tc67;
    }

    /**
     * Sets the value of the tc67 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc67(BigInteger value) {
        this.tc67 = value;
    }

    @Transient
    public boolean isSetTc67() {
        return (this.tc67 != null);
    }

    /**
     * Gets the value of the tc68 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC68", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC68")
    public BigInteger getTc68() {
        return tc68;
    }

    /**
     * Sets the value of the tc68 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc68(BigInteger value) {
        this.tc68 = value;
    }

    @Transient
    public boolean isSetTc68() {
        return (this.tc68 != null);
    }

    /**
     * Gets the value of the tc69 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC69", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC69")
    public BigInteger getTc69() {
        return tc69;
    }

    /**
     * Sets the value of the tc69 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc69(BigInteger value) {
        this.tc69 = value;
    }

    @Transient
    public boolean isSetTc69() {
        return (this.tc69 != null);
    }

    /**
     * Gets the value of the tc70 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC70", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC70")
    public BigInteger getTc70() {
        return tc70;
    }

    /**
     * Sets the value of the tc70 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc70(BigInteger value) {
        this.tc70 = value;
    }

    @Transient
    public boolean isSetTc70() {
        return (this.tc70 != null);
    }

    /**
     * Gets the value of the tc71 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC71", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC71")
    public BigInteger getTc71() {
        return tc71;
    }

    /**
     * Sets the value of the tc71 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc71(BigInteger value) {
        this.tc71 = value;
    }

    @Transient
    public boolean isSetTc71() {
        return (this.tc71 != null);
    }

    /**
     * Gets the value of the tc72 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC72", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC72")
    public BigInteger getTc72() {
        return tc72;
    }

    /**
     * Sets the value of the tc72 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc72(BigInteger value) {
        this.tc72 = value;
    }

    @Transient
    public boolean isSetTc72() {
        return (this.tc72 != null);
    }

    /**
     * Gets the value of the tc73 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC73", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC73")
    public BigInteger getTc73() {
        return tc73;
    }

    /**
     * Sets the value of the tc73 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc73(BigInteger value) {
        this.tc73 = value;
    }

    @Transient
    public boolean isSetTc73() {
        return (this.tc73 != null);
    }

    /**
     * Gets the value of the tc74 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC74", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC74")
    public BigInteger getTc74() {
        return tc74;
    }

    /**
     * Sets the value of the tc74 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc74(BigInteger value) {
        this.tc74 = value;
    }

    @Transient
    public boolean isSetTc74() {
        return (this.tc74 != null);
    }

    /**
     * Gets the value of the tc75 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC75", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC75")
    public BigInteger getTc75() {
        return tc75;
    }

    /**
     * Sets the value of the tc75 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc75(BigInteger value) {
        this.tc75 = value;
    }

    @Transient
    public boolean isSetTc75() {
        return (this.tc75 != null);
    }

    /**
     * Gets the value of the tc76 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC76", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC76")
    public BigInteger getTc76() {
        return tc76;
    }

    /**
     * Sets the value of the tc76 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc76(BigInteger value) {
        this.tc76 = value;
    }

    @Transient
    public boolean isSetTc76() {
        return (this.tc76 != null);
    }

    /**
     * Gets the value of the tc77 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC77", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC77")
    public BigInteger getTc77() {
        return tc77;
    }

    /**
     * Sets the value of the tc77 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc77(BigInteger value) {
        this.tc77 = value;
    }

    @Transient
    public boolean isSetTc77() {
        return (this.tc77 != null);
    }

    /**
     * Gets the value of the tc78 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC78", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC78")
    public BigInteger getTc78() {
        return tc78;
    }

    /**
     * Sets the value of the tc78 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc78(BigInteger value) {
        this.tc78 = value;
    }

    @Transient
    public boolean isSetTc78() {
        return (this.tc78 != null);
    }

    /**
     * Gets the value of the tc79 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC79", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC79")
    public BigInteger getTc79() {
        return tc79;
    }

    /**
     * Sets the value of the tc79 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc79(BigInteger value) {
        this.tc79 = value;
    }

    @Transient
    public boolean isSetTc79() {
        return (this.tc79 != null);
    }

    /**
     * Gets the value of the tc80 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC80", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC80")
    public BigInteger getTc80() {
        return tc80;
    }

    /**
     * Sets the value of the tc80 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc80(BigInteger value) {
        this.tc80 = value;
    }

    @Transient
    public boolean isSetTc80() {
        return (this.tc80 != null);
    }

    /**
     * Gets the value of the tc81 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC81", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC81")
    public BigInteger getTc81() {
        return tc81;
    }

    /**
     * Sets the value of the tc81 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc81(BigInteger value) {
        this.tc81 = value;
    }

    @Transient
    public boolean isSetTc81() {
        return (this.tc81 != null);
    }

    /**
     * Gets the value of the tc82 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC82", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC82")
    public BigInteger getTc82() {
        return tc82;
    }

    /**
     * Sets the value of the tc82 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc82(BigInteger value) {
        this.tc82 = value;
    }

    @Transient
    public boolean isSetTc82() {
        return (this.tc82 != null);
    }

    /**
     * Gets the value of the tc83 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC83", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC83")
    public BigInteger getTc83() {
        return tc83;
    }

    /**
     * Sets the value of the tc83 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc83(BigInteger value) {
        this.tc83 = value;
    }

    @Transient
    public boolean isSetTc83() {
        return (this.tc83 != null);
    }

    /**
     * Gets the value of the tc84 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC84", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC84")
    public BigInteger getTc84() {
        return tc84;
    }

    /**
     * Sets the value of the tc84 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc84(BigInteger value) {
        this.tc84 = value;
    }

    @Transient
    public boolean isSetTc84() {
        return (this.tc84 != null);
    }

    /**
     * Gets the value of the tc85 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC85", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC85")
    public BigInteger getTc85() {
        return tc85;
    }

    /**
     * Sets the value of the tc85 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc85(BigInteger value) {
        this.tc85 = value;
    }

    @Transient
    public boolean isSetTc85() {
        return (this.tc85 != null);
    }

    /**
     * Gets the value of the tc86 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC86", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC86")
    public BigInteger getTc86() {
        return tc86;
    }

    /**
     * Sets the value of the tc86 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc86(BigInteger value) {
        this.tc86 = value;
    }

    @Transient
    public boolean isSetTc86() {
        return (this.tc86 != null);
    }

    /**
     * Gets the value of the tc87 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC87", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC87")
    public BigInteger getTc87() {
        return tc87;
    }

    /**
     * Sets the value of the tc87 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc87(BigInteger value) {
        this.tc87 = value;
    }

    @Transient
    public boolean isSetTc87() {
        return (this.tc87 != null);
    }

    /**
     * Gets the value of the tc88 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC88", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC88")
    public BigInteger getTc88() {
        return tc88;
    }

    /**
     * Sets the value of the tc88 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc88(BigInteger value) {
        this.tc88 = value;
    }

    @Transient
    public boolean isSetTc88() {
        return (this.tc88 != null);
    }

    /**
     * Gets the value of the tc89 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC89", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC89")
    public BigInteger getTc89() {
        return tc89;
    }

    /**
     * Sets the value of the tc89 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc89(BigInteger value) {
        this.tc89 = value;
    }

    @Transient
    public boolean isSetTc89() {
        return (this.tc89 != null);
    }

    /**
     * Gets the value of the tc90 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC90", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC90")
    public BigInteger getTc90() {
        return tc90;
    }

    /**
     * Sets the value of the tc90 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc90(BigInteger value) {
        this.tc90 = value;
    }

    @Transient
    public boolean isSetTc90() {
        return (this.tc90 != null);
    }

    /**
     * Gets the value of the tc91 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC91", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC91")
    public BigInteger getTc91() {
        return tc91;
    }

    /**
     * Sets the value of the tc91 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc91(BigInteger value) {
        this.tc91 = value;
    }

    @Transient
    public boolean isSetTc91() {
        return (this.tc91 != null);
    }

    /**
     * Gets the value of the tc92 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC92", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC92")
    public BigInteger getTc92() {
        return tc92;
    }

    /**
     * Sets the value of the tc92 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc92(BigInteger value) {
        this.tc92 = value;
    }

    @Transient
    public boolean isSetTc92() {
        return (this.tc92 != null);
    }

    /**
     * Gets the value of the tc93 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC93", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC93")
    public BigInteger getTc93() {
        return tc93;
    }

    /**
     * Sets the value of the tc93 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc93(BigInteger value) {
        this.tc93 = value;
    }

    @Transient
    public boolean isSetTc93() {
        return (this.tc93 != null);
    }

    /**
     * Gets the value of the tc94 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC94", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC94")
    public BigInteger getTc94() {
        return tc94;
    }

    /**
     * Sets the value of the tc94 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc94(BigInteger value) {
        this.tc94 = value;
    }

    @Transient
    public boolean isSetTc94() {
        return (this.tc94 != null);
    }

    /**
     * Gets the value of the tc95 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC95", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC95")
    public BigInteger getTc95() {
        return tc95;
    }

    /**
     * Sets the value of the tc95 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc95(BigInteger value) {
        this.tc95 = value;
    }

    @Transient
    public boolean isSetTc95() {
        return (this.tc95 != null);
    }

    /**
     * Gets the value of the tc96 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC96", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC96")
    public BigInteger getTc96() {
        return tc96;
    }

    /**
     * Sets the value of the tc96 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc96(BigInteger value) {
        this.tc96 = value;
    }

    @Transient
    public boolean isSetTc96() {
        return (this.tc96 != null);
    }

    /**
     * Gets the value of the tc97 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC97", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC97")
    public BigInteger getTc97() {
        return tc97;
    }

    /**
     * Sets the value of the tc97 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc97(BigInteger value) {
        this.tc97 = value;
    }

    @Transient
    public boolean isSetTc97() {
        return (this.tc97 != null);
    }

    /**
     * Gets the value of the tc98 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC98", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC98")
    public BigInteger getTc98() {
        return tc98;
    }

    /**
     * Sets the value of the tc98 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc98(BigInteger value) {
        this.tc98 = value;
    }

    @Transient
    public boolean isSetTc98() {
        return (this.tc98 != null);
    }

    /**
     * Gets the value of the tc99 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "FCT_TC99", precision = 10, scale = 0)
    @org.cern.cms.csc.dw.model.annotation.OlapMeasure(aggregator = org.cern.cms.csc.dw.model.annotation.OlapMeasure.AggregatorType.SUM, name = "TC99")
    public BigInteger getTc99() {
        return tc99;
    }

    /**
     * Sets the value of the tc99 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTc99(BigInteger value) {
        this.tc99 = value;
    }

    @Transient
    public boolean isSetTc99() {
        return (this.tc99 != null);
    }
    
//--simple--preserve

    @Override
    public void onReceive(org.cern.cms.csc.dw.dao.EntityDaoLocal eDao) throws org.cern.cms.csc.dw.exception.OnReceiveProcessingException {
        super.onReceive(eDao);
        try {
            setDescriptions(eDao.getEntityById(org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE.class, getVersion()));
        } catch (jsf.bean.gui.exception.InvalidEntityClassException ex) {
            throw new org.cern.cms.csc.dw.exception.OnReceiveProcessingException(ex);
        }
    }

    @Override
    public void onSave(org.cern.cms.csc.dw.dao.EntityDaoLocal eDao, boolean queued) throws org.cern.cms.csc.dw.exception.OnSaveProcessingException {
        super.onSave(eDao, queued);
        if (queued) {
            if (isSetDescriptions()) {
                try {
                    setDescriptions(eDao.getEntityById(org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE.class, getVersion()));
                } catch (jsf.bean.gui.exception.InvalidEntityClassException ex) {
                    throw new org.cern.cms.csc.dw.exception.OnSaveProcessingException(ex);
                }
            }
        }
    }

    @javax.xml.bind.annotation.XmlTransient
    private java.util.Map<String, BigInteger> counters;
    @javax.xml.bind.annotation.XmlTransient
    private static java.util.regex.Pattern counterPropertyPattern = java.util.regex.Pattern.compile("tc\\d\\d");

    @Transient
    public java.util.Map<String, BigInteger> getCounters() {
        if (counters == null) {
            try {
                counters = new java.util.HashMap<String, BigInteger>();
                org.cern.cms.csc.dw.model.dse.TmbCounterDescriptionDSE counterNames = getDescriptions();
                java.util.Map<String, Object> propertyValues = new java.util.HashMap<String, Object>();
                org.apache.commons.beanutils.BeanUtils.populate(this, propertyValues); // get a property name to value map for all properties of this bean
                for (java.util.Map.Entry<String, Object> entry: propertyValues.entrySet()) {
                    if (counterPropertyPattern.matcher(entry.getKey()).matches()) { // this is a counter property - that's what we're interested in
                        String counterName = org.apache.commons.beanutils.BeanUtils.getProperty(counterNames, entry.getKey() + "Description"); // get description for this name
                        counters.put(counterName, (BigInteger) entry.getValue());
                    }
                }
            } catch (IllegalAccessException iaex) {
                throw new RuntimeException(iaex);
            } catch (java.lang.reflect.InvocationTargetException itex) {
                throw new RuntimeException(itex);
            } catch (NoSuchMethodException nsmex) {
                throw new RuntimeException(nsmex);
            }
        }
        return counters;
    }
    
//--simple--preserve

}
