CREATE INDEX CDW_SYN_CMP_FK_IDX ON CDW_COMPONENT_SYNONYMS (SYN_CMP_ID)
/
CREATE INDEX CDW_CCP_CHILD_IDX ON CDW_COMPONENT_CLASS_PARENTS (CCP_CHILD_CCL_ID)
/
CREATE INDEX CDW_CMP_CCL_FK_IDX ON CDW_COMPONENTS (CMP_CCL_ID)
/
CREATE INDEX CDW_LCL_INVERSE_LCL_FK_IDX ON CDW_COMPONENT_LINK_CLASSES (LCL_INVERSE_LCL_ID)
/
CREATE INDEX CDW_LCL_PARENT_LCL_FK_IDX ON CDW_COMPONENT_LINK_CLASSES (LCL_PARENT_LCL_ID)
/