#!/bin/bash

  while [ "y" == "y" ]
  do

# comment 1: there should be a sleep after wget: otherwise cp command copies the other chamber file (wget does very long) 
# comment 2: the sleep (indiscated as ***) should be about the same as the period of measurements 
# (otherwise we  put the same data in the  /home/fast/pvss_fsm/data/http/refs/emudcs/fcfeb_c e.g. (if the period is frequent)) 
#
#
#

wget -b -O - "http://pcmsucr2.cern.ch/PVSS?ref=refs/emudcs/lv_query.htmlRef&dp=System1:LowVoltage/CSCdm2r2c01LV_1&chamber=MEm2_2_01" > temp
sleep 10;
cp /home/fast/pvss_fsm/data/http/refs/emudcs/lv_query.html /afs/cern.ch/cms/MUON/csc/info_pool/DCS/ch_01.html

wget -b -O - "http://pcmsucr2.cern.ch/PVSS?ref=refs/emudcs/lv_query.htmlRef&dp=System1:LowVoltage/CSCdm2r2c31LV_1&chamber=MEm2_2_31" > temp
sleep 10;
cp /home/fast/pvss_fsm/data/http/refs/emudcs/lv_query.html /afs/cern.ch/cms/MUON/csc/info_pool/DCS/ch_31.html

wget -b -O - "http://pcmsucr2.cern.ch/PVSS?ref=refs/emudcs/lv_query.htmlRef&dp=System1:LowVoltage/CSCdm2r2c33LV_1&chamber=MEm2_2_33" > temp
sleep 10;
cp /home/fast/pvss_fsm/data/http/refs/emudcs/lv_query.html /afs/cern.ch/cms/MUON/csc/info_pool/DCS/ch_33.html

wget -b -O - "http://pcmsucr2.cern.ch/PVSS?ref=refs/emudcs/lv_query.htmlRef&dp=System1:LowVoltage/CSCdm2r2c35LV_1&chamber=MEm2_2_35" > temp
sleep 10;
cp /home/fast/pvss_fsm/data/http/refs/emudcs/lv_query.html /afs/cern.ch/cms/MUON/csc/info_pool/DCS/ch_35.html


cp /home/fast/pvss_fsm/data/http/refs/emudcs/*.png /afs/cern.ch/cms/MUON/csc/info_pool/DCS/.

sleep 1560; # (***) the sleep should be about the same as the period of measurements 1560 = 26 minutes

delete_processes_by_name "'wget -b'" > temp

rm -f wget-log*  > temp
    
    sleep 30
  done
