//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.cern.cms.csc.exsys.re.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conclusionTriggerTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="conclusionTriggerTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Open"/>
 *     &lt;enumeration value="Update"/>
 *     &lt;enumeration value="Close"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "conclusionTriggerTypeType")
@XmlEnum
public enum ConclusionTriggerType {

    @XmlEnumValue("Open")
    OPEN("Open"),
    @XmlEnumValue("Update")
    UPDATE("Update"),
    @XmlEnumValue("Close")
    CLOSE("Close");
    private final String value;

    ConclusionTriggerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConclusionTriggerType fromValue(String v) {
        for (ConclusionTriggerType c: ConclusionTriggerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String getValue() {
        return value;
    }

}
