#!/bin/sh

# Red Hat Linux VNC session startup script
# the following is corrected by me 07/05/2006
###exec /etc/X11/xinit/xinitrc
cp $HOME/.vnc/emudcs.cern.ch:1.log $HOME/.vnc/`date +'log'_%h_%d_%Y_%H_%M`
exec $HOME/.vnc/my_xinitrc
