//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.21 at 05:10:42 PM CEST 
//


package org.cern.cms.csc.dw.model.test;

import org.jvnet.jaxb2_commons.xml.bind.ContextPathAware;

public class RoundtripTest
    extends org.jvnet.hyperjaxb3.ejb.test.RoundtripTest
    implements ContextPathAware
{


    public String getContextPath() {
        return "org.cern.cms.csc.dw.model.fact:org.cern.cms.csc.exsys.re.model:org.cern.cms.csc.dw.model.ontology:org.cern.cms.csc.dw.service:org.cern.cms.csc.dw.model.dse";
    }

}
