#!/bin/bash



killall emudcs_watchdog_crontab_wrap
killall emudcs_watchdog_crontab
killall emudcs_watch_dog
killall emudcs_exe_wrap
killall simple_config_plus_dcs_new.exe
killall cc
killall read_single
