  CREATE TABLE "EMUCDB_FSM_TYPES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IS_CU" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DEFAULT_UI" VARCHAR2(255 BYTE), 
	 CONSTRAINT "EMUCDB_FSM_TYPES_PK" PRIMARY KEY ("ID") ENABLE
   );

  CREATE TABLE "EMUCDB_PARAMETERS" 
   (	"NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMUCDB_PARAMETERS_PK" PRIMARY KEY ("NAME") ENABLE
   );

  CREATE TABLE "EMUCDB_DEVICES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"HW_ID" VARCHAR2(20 BYTE), 
	"FSM_TYPE" NUMBER, 
	"FSM_UI" VARCHAR2(255 BYTE), 
	"LABEL" VARCHAR2(128 BYTE), 
	"INFO" VARCHAR2(255 BYTE), 
	"LOCATION" NUMBER, 
	"IS_ROOT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"FSM_DOMAIN" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"FSM_OBJ" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMUCDB_DEVICES_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "EMUCDB_DEVICES_ITEMS_FK" FOREIGN KEY ("ID")
	  REFERENCES "ITEMS" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "EMUCDB_DEVICES_FSM_TYPES_FK" FOREIGN KEY ("FSM_TYPE")
	  REFERENCES "EMUCDB_FSM_TYPES" ("ID") ENABLE
   );

  CREATE TABLE "EMUCDB_HOST_CONF" 
   (	"HOSTNAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"CONF_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"FSM_DOMAIN" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMUCDB_HOST_CONF_PK" PRIMARY KEY ("HOSTNAME", "CONF_NAME", "FSM_DOMAIN")
   );

  CREATE SEQUENCE "EMUCDB_FSM_TYPES_SEQ"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 0 CACHE 20 NOORDER  NOCYCLE;

  CREATE OR REPLACE TRIGGER "EMUCDB_FSM_TYPES_SEQ_TRIG" before insert on "EMUCDB_FSM_TYPES"    for each row begin     if inserting then       if :NEW."ID" is null then          select EMUCDB_FSM_TYPES_SEQ.nextval into :NEW."ID" from dual;       end if;    end if; end;;

  ALTER TRIGGER "EMUCDB_FSM_TYPES_SEQ_TRIG" ENABLE;

  INSERT INTO EMUCDB_PARAMETERS(NAME, VALUE) VALUES ('emucdb_version', '1.0');

  INSERT INTO EMUCDB_PARAMETERS(NAME, VALUE) VALUES ('fsm_generator_default_fill', 'generated-dummy');

  INSERT INTO EMUCDB_HOST_CONF(HOSTNAME, CONF_NAME, FSM_DOMAIN) VALUES ('macfrank', '904_LV', 'CMS_CSC_LV_CAN2');
